// 主要国际机场中文映射表
const airportZhMapping = {
  // 亚洲
  'SIN': { city_zh: '新加坡', name_zh: '新加坡樟宜国际机场' },
  'PEK': { city_zh: '北京', name_zh: '北京首都国际机场' },
  'SHA': { city_zh: '上海', name_zh: '上海虹桥国际机场' },
  'PVG': { city_zh: '上海', name_zh: '上海浦东国际机场' },
  'CAN': { city_zh: '广州', name_zh: '广州白云国际机场' },
  'SZX': { city_zh: '深圳', name_zh: '深圳宝安国际机场' },
  'CTU': { city_zh: '成都', name_zh: '成都双流国际机场' },
  'HGH': { city_zh: '杭州', name_zh: '杭州萧山国际机场' },
  'XIY': { city_zh: '西安', name_zh: '西安咸阳国际机场' },
  'NKG': { city_zh: '南京', name_zh: '南京禄口国际机场' },
  'WUH': { city_zh: '武汉', name_zh: '武汉天河国际机场' },
  'CKG': { city_zh: '重庆', name_zh: '重庆江北国际机场' },
  'KMG': { city_zh: '昆明', name_zh: '昆明长水国际机场' },
  'BAV': { city_zh: '包头', name_zh: '包头东河机场' },
  'WUA': { city_zh: '乌海', name_zh: '乌海机场' },
  'EJN': { city_zh: '额济纳', name_zh: '额济纳桃来机场' },
  'RLK': { city_zh: '巴彦淖尔', name_zh: '巴彦淖尔天吉泰机场' },
  'DSN': { city_zh: '鄂尔多斯', name_zh: '鄂尔多斯伊金霍洛国际机场' },
  'YLN': { city_zh: '伊春', name_zh: '伊春林都机场' },
  'HEK': { city_zh: '黑河', name_zh: '黑河瑷珲机场' },
  'FYJ': { city_zh: '抚远', name_zh: '抚远东极机场' },
  'JSJ': { city_zh: '建三江', name_zh: '建三江湿地机场' },
  'YKH': { city_zh: '营口', name_zh: '营口兰旗机场' },
  'SQA': { city_zh: '四平', name_zh: '四平机场' },
  'LDS': { city_zh: '伊春', name_zh: '伊春林都机场' },
  'JXA': { city_zh: '鸡西', name_zh: '鸡西兴凯湖机场' },
  'DGQ': { city_zh: '五大连池', name_zh: '五大连池德都机场' },
  'LBE': { city_zh: '长白', name_zh: '长白机场' },
  'TLQ': { city_zh: '吐鲁番', name_zh: '吐鲁番交河机场' },
  'NLT': { city_zh: '新源', name_zh: '新源那拉提机场' },
  'HMI': { city_zh: '哈密', name_zh: '哈密机场' },
  'KCA': { city_zh: '库车', name_zh: '库车龟兹机场' },
  'ACF': { city_zh: '富蕴', name_zh: '富蕴可可托海机场' },
  'KJI': { city_zh: '喀纳斯', name_zh: '喀纳斯机场' },
  'SHF': { city_zh: '石河子', name_zh: '石河子花园机场' },
  'HTL': { city_zh: '和田', name_zh: '和田机场' },
  'QSZ': { city_zh: '莎车', name_zh: '莎车叶尔羌机场' },
  'WTC': { city_zh: '图木舒克', name_zh: '图木舒克唐王城机场' },
  'HQS': { city_zh: '塔什库尔干', name_zh: '塔什库尔干红其拉甫机场' },
  'YUZ': { city_zh: '榆林', name_zh: '榆林榆阳机场' },
  'UUN': { city_zh: '二连浩特', name_zh: '二连浩特赛乌素机场' },
  'NZH': { city_zh: '满洲里', name_zh: '满洲里西郊机场' },
  'NGQ': { city_zh: '阿里', name_zh: '阿里昆莎机场' },
  'RKZ': { city_zh: '日喀则', name_zh: '日喀则和平机场' },
  'LZY': { city_zh: '林芝', name_zh: '林芝米林机场' },
  'DCY': { city_zh: '稻城', name_zh: '稻城亚丁机场' },
  'GZG': { city_zh: '甘孜', name_zh: '甘孜康定机场' },
  'AHJ': { city_zh: '阿坝', name_zh: '阿坝红原机场' },
  'AVA': { city_zh: '安顺', name_zh: '安顺黄果树机场' },
  'LLB': { city_zh: '荔波', name_zh: '荔波机场' },
  'HCZ': { city_zh: '郴州', name_zh: '郴州北湖机场' },
  'WUG': { city_zh: '武冈', name_zh: '武冈机场' },
  'LLF': { city_zh: '永州', name_zh: '永州零陵机场' },
  'AEB': { city_zh: '百色', name_zh: '百色巴马机场' },
  'LZH': { city_zh: '柳州', name_zh: '柳州白莲机场' },
  'YLX': { city_zh: '玉林', name_zh: '玉林福绵机场' },
  'BPX': { city_zh: '昌都', name_zh: '昌都邦达机场' },
  'GXH': { city_zh: '夏河', name_zh: '甘南夏河机场' },
  'LNL': { city_zh: '陇南', name_zh: '陇南成县机场' },
  'JIC': { city_zh: '金昌', name_zh: '金昌金川机场' },
  'IQN': { city_zh: '庆阳', name_zh: '庆阳机场' },
  'HZG': { city_zh: '汉中', name_zh: '汉中城固机场' },
  'AKA': { city_zh: '安康', name_zh: '安康富强机场' },
  'WDS': { city_zh: '十堰', name_zh: '十堰武当山机场' },
  'XAI': { city_zh: '信阳', name_zh: '信阳明港机场' },
  'LUK': { city_zh: '六安', name_zh: '六安机场' },
  'KOW': { city_zh: '赣州', name_zh: '赣州黄金国际机场' },
  'JDZ': { city_zh: '景德镇', name_zh: '景德镇罗家机场' },
  'SQJ': { city_zh: '三明', name_zh: '三明沙县机场' },
  'WUS': { city_zh: '武夷山', name_zh: '武夷山机场' },
  'LYI': { city_zh: '临沂', name_zh: '临沂启阳机场' },
  'DOY': { city_zh: '东营', name_zh: '东营胜利机场' },
  'WEF': { city_zh: '潍坊', name_zh: '潍坊机场' },
  'RZH': { city_zh: '日照', name_zh: '日照山字河机场' },
  'TNA': { city_zh: '济南', name_zh: '济南遥墙国际机场' },
  'YNT': { city_zh: '烟台', name_zh: '烟台蓬莱国际机场' },
  'WEH': { city_zh: '威海', name_zh: '威海大水泊机场' },
  'HIA': { city_zh: '淮安', name_zh: '淮安涟水国际机场' },
  'LYG': { city_zh: '连云港', name_zh: '连云港花果山机场' },
  'YTY': { city_zh: '扬州', name_zh: '扬州泰州国际机场' },
  'RUG': { city_zh: '如皋', name_zh: '如皋机场' },
  'PVG': { city_zh: '上海', name_zh: '上海浦东国际机场' },
  'SHA': { city_zh: '上海', name_zh: '上海虹桥国际机场' },
  'HYN': { city_zh: '台州', name_zh: '台州路桥机场' },
  'JUZ': { city_zh: '衢州', name_zh: '衢州机场' },
  'HSN': { city_zh: '舟山', name_zh: '舟山普陀山机场' },
  'YIW': { city_zh: '义乌', name_zh: '义乌机场' },
  'HGH': { city_zh: '杭州', name_zh: '杭州萧山国际机场' },
  'FUG': { city_zh: '阜阳', name_zh: '阜阳西关机场' },
  'AQG': { city_zh: '安庆', name_zh: '安庆天柱山机场' },
  'TXN': { city_zh: '黄山', name_zh: '黄山屯溪国际机场' },
  'BHY': { city_zh: '北海', name_zh: '北海福成机场' },
  'KWL': { city_zh: '桂林', name_zh: '桂林两江国际机场' },
  'LZH': { city_zh: '柳州', name_zh: '柳州白莲机场' },
  'DYG': { city_zh: '张家界', name_zh: '张家界荷花国际机场' },
  'CGD': { city_zh: '常德', name_zh: '常德桃花源机场' },
  'HJJ': { city_zh: '怀化', name_zh: '怀化芷江机场' },
  'CSX': { city_zh: '长沙', name_zh: '长沙黄花国际机场' },
  'XFN': { city_zh: '襄阳', name_zh: '襄阳刘集机场' },
  'YIH': { city_zh: '宜昌', name_zh: '宜昌三峡机场' },
  'ENH': { city_zh: '恩施', name_zh: '恩施许家坪机场' },
  'NNY': { city_zh: '南阳', name_zh: '南阳姜营机场' },
  'LYA': { city_zh: '洛阳', name_zh: '洛阳北郊机场' },
  'HDG': { city_zh: '邯郸', name_zh: '邯郸机场' },
  'TVS': { city_zh: '唐山', name_zh: '唐山三女河机场' },
  'BPE': { city_zh: '秦皇岛', name_zh: '秦皇岛北戴河机场' },
  'LUM': { city_zh: '芒市', name_zh: '德宏芒市机场' },
  'BSD': { city_zh: '保山', name_zh: '保山机场' },
  'SYM': { city_zh: '普洱', name_zh: '普洱思茅机场' },
  'LNJ': { city_zh: '临沧', name_zh: '临沧机场' },
  'ZAT': { city_zh: '昭通', name_zh: '昭通机场' },
  'WNH': { city_zh: '文山', name_zh: '文山砚山机场' },
  'DLU': { city_zh: '大理', name_zh: '大理机场' },
  'LJG': { city_zh: '丽江', name_zh: '丽江三义国际机场' },
  'JHG': { city_zh: '西双版纳', name_zh: '西双版纳嘎洒国际机场' },
  'DIG': { city_zh: '香格里拉', name_zh: '迪庆香格里拉机场' },
  'MIG': { city_zh: '绵阳', name_zh: '绵阳南郊机场' },
  'NAO': { city_zh: '南充', name_zh: '南充高坪机场' },
  'YBP': { city_zh: '宜宾', name_zh: '宜宾五粮液机场' },
  'LZO': { city_zh: '泸州', name_zh: '泸州云龙机场' },
  'DAX': { city_zh: '达州', name_zh: '达州金垭机场' },
  'GYS': { city_zh: '广元', name_zh: '广元盘龙机场' },
  'KGT': { city_zh: '康定', name_zh: '康定机场' },
  'JZH': { city_zh: '九寨沟', name_zh: '九寨黄龙机场' },
  'DCY': { city_zh: '稻城', name_zh: '稻城亚丁机场' },
  'AEB': { city_zh: '百色', name_zh: '百色巴马机场' },
  'ZUH': { city_zh: '珠海', name_zh: '珠海金湾机场' },
  'SWA': { city_zh: '揭阳', name_zh: '揭阳潮汕国际机场' },
  'MXZ': { city_zh: '梅县', name_zh: '梅县机场' },
  'ZHA': { city_zh: '湛江', name_zh: '湛江吴川机场' },
  'BAR': { city_zh: '琼海', name_zh: '琼海博鳌机场' },
  'FUO': { city_zh: '佛山', name_zh: '佛山沙堤机场' },
  'ZQZ': { city_zh: '张家口', name_zh: '张家口宁远机场' },
  'CDE': { city_zh: '承德', name_zh: '承德普宁机场' },
  'JNG': { city_zh: '济宁', name_zh: '济宁大安机场' },
  'JGS': { city_zh: '井冈山', name_zh: '井冈山机场' },
  'KJH': { city_zh: '凯里', name_zh: '黄平机场' },
  'ACX': { city_zh: '兴义', name_zh: '兴义万峰林机场' },
  'TEN': { city_zh: '铜仁', name_zh: '铜仁凤凰机场' },
  'HZH': { city_zh: '黎平', name_zh: '黎平机场' },
  'ZYI': { city_zh: '遵义', name_zh: '遵义新舟机场' },
  'WMT': { city_zh: '茅台', name_zh: '遵义茅台机场' },
  'ENH': { city_zh: '恩施', name_zh: '恩施许家坪机场' },
  'XAI': { city_zh: '信阳', name_zh: '信阳明港机场' },
  'NNY': { city_zh: '南阳', name_zh: '南阳姜营机场' },
  'AKA': { city_zh: '安康', name_zh: '安康富强机场' },
  'ENY': { city_zh: '延安', name_zh: '延安南泥湾机场' },
  'UYN': { city_zh: '榆林', name_zh: '榆林榆阳机场' },
  'IQN': { city_zh: '庆阳', name_zh: '庆阳机场' },
  'JGN': { city_zh: '嘉峪关', name_zh: '嘉峪关酒泉机场' },
  'DNH': { city_zh: '敦煌', name_zh: '敦煌机场' },
  'GOQ': { city_zh: '格尔木', name_zh: '格尔木机场' },
  'HXD': { city_zh: '德令哈', name_zh: '德令哈机场' },
  'YUS': { city_zh: '玉树', name_zh: '玉树巴塘机场' },
  'ZHY': { city_zh: '中卫', name_zh: '中卫沙坡头机场' },
  'ZQZ': { city_zh: '张家口', name_zh: '张家口宁远机场' },
  'NLT': { city_zh: '新源', name_zh: '新源那拉提机场' },
  'KJI': { city_zh: '喀纳斯', name_zh: '喀纳斯机场' },
  'TLQ': { city_zh: '吐鲁番', name_zh: '吐鲁番交河机场' },
  'SHE': { city_zh: '沈阳', name_zh: '沈阳桃仙国际机场' },
  'PKX': { city_zh: '北京', name_zh: '北京大兴国际机场' },
  'TFU': { city_zh: '成都', name_zh: '成都天府国际机场' },
  'XMN': { city_zh: '厦门', name_zh: '厦门高崎国际机场' },
  'FOC': { city_zh: '福州', name_zh: '福州长乐国际机场' },
  'CSX': { city_zh: '长沙', name_zh: '长沙黄花国际机场' },
  'HFE': { city_zh: '合肥', name_zh: '合肥新桥国际机场' },
  'NNG': { city_zh: '南宁', name_zh: '南宁吴圩国际机场' },
  'CGO': { city_zh: '郑州', name_zh: '郑州新郑国际机场' },
  'TSN': { city_zh: '天津', name_zh: '天津滨海国际机场' },
  'DLC': { city_zh: '大连', name_zh: '大连周水子国际机场' },
  'TAO': { city_zh: '青岛', name_zh: '青岛胶东国际机场' },
  'HRB': { city_zh: '哈尔滨', name_zh: '哈尔滨太平国际机场' },
  'CGQ': { city_zh: '长春', name_zh: '长春龙嘉国际机场' },
  'SJW': { city_zh: '石家庄', name_zh: '石家庄正定国际机场' },
  'LHW': { city_zh: '兰州', name_zh: '兰州中川国际机场' },
  'URC': { city_zh: '乌鲁木齐', name_zh: '乌鲁木齐地窝堡国际机场' },
  'KHN': { city_zh: '南昌', name_zh: '南昌昌北国际机场' },
  'KOW': { city_zh: '赣州', name_zh: '赣州黄金国际机场' },
  'NGB': { city_zh: '宁波', name_zh: '宁波栎社国际机场' },
  'WNZ': { city_zh: '温州', name_zh: '温州龙湾国际机场' },
  'HYN': { city_zh: '台州', name_zh: '台州路桥机场' },
  'HET': { city_zh: '呼和浩特', name_zh: '呼和浩特白塔国际机场' },
  'INC': { city_zh: '银川', name_zh: '银川河东国际机场' },
  'XNN': { city_zh: '西宁', name_zh: '西宁曹家堡国际机场' },
  'LXA': { city_zh: '拉萨', name_zh: '拉萨贡嘎国际机场' },
  'SYX': { city_zh: '三亚', name_zh: '三亚凤凰国际机场' },
  'KWE': { city_zh: '贵阳', name_zh: '贵阳龙洞堡国际机场' },
  'TXN': { city_zh: '黄山', name_zh: '黄山屯溪国际机场' },
  'JHG': { city_zh: '西双版纳', name_zh: '西双版纳嘎洒国际机场' },
  'LJG': { city_zh: '丽江', name_zh: '丽江三义国际机场' },
  'DLU': { city_zh: '大理', name_zh: '大理机场' },
  'DIG': { city_zh: '香格里拉', name_zh: '迪庆香格里拉机场' },
  'MIG': { city_zh: '绵阳', name_zh: '绵阳南郊机场' },
  'NAO': { city_zh: '南充', name_zh: '南充高坪机场' },
  'YBP': { city_zh: '宜宾', name_zh: '宜宾五粮液机场' },
  'LZO': { city_zh: '泸州', name_zh: '泸州云龙机场' },
  'WXN': { city_zh: '万州', name_zh: '万州五桥机场' },
  'AKU': { city_zh: '阿克苏', name_zh: '阿克苏红旗坡机场' },
  'HTN': { city_zh: '和田', name_zh: '和田机场' },
  'KHG': { city_zh: '喀什', name_zh: '喀什徕宁国际机场' },
  'KRL': { city_zh: '库尔勒', name_zh: '库尔勒梨城机场' },
  'YIN': { city_zh: '伊宁', name_zh: '伊宁机场' },
  'AAT': { city_zh: '阿勒泰', name_zh: '阿勒泰雪都机场' },
  'IQM': { city_zh: '且末', name_zh: '且末机场' },
  'TCG': { city_zh: '塔城', name_zh: '塔城机场' },
  'BPL': { city_zh: '博乐', name_zh: '博乐阿拉山口机场' },
  'GOQ': { city_zh: '格尔木', name_zh: '格尔木机场' },
  'DNH': { city_zh: '敦煌', name_zh: '敦煌机场' },
  'JGN': { city_zh: '嘉峪关', name_zh: '嘉峪关酒泉机场' },
  'YUZ': { city_zh: '榆林', name_zh: '榆林榆阳机场' },
  'ENY': { city_zh: '延安', name_zh: '延安南泥湾机场' },
  'HZG': { city_zh: '汉中', name_zh: '汉中城固机场' },
  'CIH': { city_zh: '长治', name_zh: '长治王村机场' },
  'TYN': { city_zh: '太原', name_zh: '太原武宿国际机场' },
  'DAT': { city_zh: '大同', name_zh: '大同云冈机场' },
  'YCU': { city_zh: '运城', name_zh: '运城盐湖国际机场' },
  'LLV': { city_zh: '吕梁', name_zh: '吕梁大武机场' },
  'XIL': { city_zh: '锡林浩特', name_zh: '锡林浩特机场' },
  'HLD': { city_zh: '海拉尔', name_zh: '呼伦贝尔海拉尔机场' },
  'NZH': { city_zh: '满洲里', name_zh: '满洲里西郊机场' },
  'YIE': { city_zh: '阿尔山', name_zh: '阿尔山伊尔施机场' },
  'HLH': { city_zh: '乌兰浩特', name_zh: '乌兰浩特机场' },
  'CIF': { city_zh: '赤峰', name_zh: '赤峰玉龙机场' },
  'TGO': { city_zh: '通辽', name_zh: '通辽机场' },
  'DQA': { city_zh: '大庆', name_zh: '大庆萨尔图机场' },
  'JMU': { city_zh: '佳木斯', name_zh: '佳木斯东郊机场' },
  'NDG': { city_zh: '齐齐哈尔', name_zh: '齐齐哈尔三家子机场' },
  'MDG': { city_zh: '牡丹江', name_zh: '牡丹江海浪国际机场' },
  'OHE': { city_zh: '漠河', name_zh: '漠河古莲机场' },
  'JNZ': { city_zh: '锦州', name_zh: '锦州湾机场' },
  'DDG': { city_zh: '丹东', name_zh: '丹东浪头机场' },
  'YNT': { city_zh: '烟台', name_zh: '烟台蓬莱国际机场' },
  'WEH': { city_zh: '威海', name_zh: '威海大水泊机场' },
  'WUX': { city_zh: '无锡', name_zh: '无锡苏南硕放国际机场' },
  'CZX': { city_zh: '常州', name_zh: '常州奔牛国际机场' },
  'HIA': { city_zh: '淮安', name_zh: '淮安涟水国际机场' },
  'YTY': { city_zh: '扬州', name_zh: '扬州泰州国际机场' },
  'XUZ': { city_zh: '徐州', name_zh: '徐州观音国际机场' },
  'LYG': { city_zh: '连云港', name_zh: '连云港花果山机场' },
  'HYN': { city_zh: '台州', name_zh: '台州路桥机场' },
  'JUZ': { city_zh: '衢州', name_zh: '衢州机场' },
  'HSN': { city_zh: '舟山', name_zh: '舟山普陀山机场' },
  'YIW': { city_zh: '义乌', name_zh: '义乌机场' },
  'JDZ': { city_zh: '景德镇', name_zh: '景德镇罗家机场' },
  'JGS': { city_zh: '井冈山', name_zh: '井冈山机场' },
  'SQJ': { city_zh: '三明', name_zh: '三明沙县机场' },
  'WUS': { city_zh: '武夷山', name_zh: '武夷山机场' },
  'LYI': { city_zh: '临沂', name_zh: '临沂启阳机场' },
  'WEF': { city_zh: '潍坊', name_zh: '潍坊机场' },
  'DOY': { city_zh: '东营', name_zh: '东营胜利机场' },
  'TNA': { city_zh: '济南', name_zh: '济南遥墙国际机场' },
  'AQG': { city_zh: '安庆', name_zh: '安庆天柱山机场' },
  'BFU': { city_zh: '蚌埠', name_zh: '蚌埠机场' },
  'FUG': { city_zh: '阜阳', name_zh: '阜阳西关机场' },
  'TEN': { city_zh: '铜仁', name_zh: '铜仁凤凰机场' },
  'ACX': { city_zh: '兴义', name_zh: '兴义万峰林机场' },
  'AVA': { city_zh: '安顺', name_zh: '安顺黄果树机场' },
  'HZH': { city_zh: '黎平', name_zh: '黎平机场' },
  'ZYI': { city_zh: '遵义', name_zh: '遵义新舟机场' },
  'WMT': { city_zh: '茅台', name_zh: '遵义茅台机场' },
  'KJH': { city_zh: '凯里', name_zh: '黄平机场' },
  'BHY': { city_zh: '北海', name_zh: '北海福成机场' },
  'KWL': { city_zh: '桂林', name_zh: '桂林两江国际机场' },
  'LZH': { city_zh: '柳州', name_zh: '柳州白莲机场' },
  'DYG': { city_zh: '张家界', name_zh: '张家界荷花国际机场' },
  'CGD': { city_zh: '常德', name_zh: '常德桃花源机场' },
  'HJJ': { city_zh: '怀化', name_zh: '怀化芷江机场' },
  'LLF': { city_zh: '永州', name_zh: '永州零陵机场' },
  'XFN': { city_zh: '襄阳', name_zh: '襄阳刘集机场' },
  'YIH': { city_zh: '宜昌', name_zh: '宜昌三峡机场' },
  'ENH': { city_zh: '恩施', name_zh: '恩施许家坪机场' },
  'WDS': { city_zh: '十堰', name_zh: '十堰武当山机场' },
  'JNG': { city_zh: '济宁', name_zh: '济宁大安机场' },
  'LYA': { city_zh: '洛阳', name_zh: '洛阳北郊机场' },
  'NNY': { city_zh: '南阳', name_zh: '南阳姜营机场' },
  'XAI': { city_zh: '信阳', name_zh: '信阳明港机场' },
  'HDG': { city_zh: '邯郸', name_zh: '邯郸机场' },
  'BPE': { city_zh: '秦皇岛', name_zh: '秦皇岛北戴河机场' },
  'TVS': { city_zh: '唐山', name_zh: '唐山三女河机场' },
  'LUM': { city_zh: '芒市', name_zh: '德宏芒市机场' },
  'BSD': { city_zh: '保山', name_zh: '保山机场' },
  'SYM': { city_zh: '普洱', name_zh: '普洱思茅机场' },
  'LNJ': { city_zh: '临沧', name_zh: '临沧机场' },
  'ZAT': { city_zh: '昭通', name_zh: '昭通机场' },
  'WNH': { city_zh: '文山', name_zh: '文山砚山机场' },
  'NGQ': { city_zh: '阿里', name_zh: '阿里昆莎机场' },
  'BPX': { city_zh: '昌都', name_zh: '昌都邦达机场' },
  'YUS': { city_zh: '玉树', name_zh: '玉树巴塘机场' },
  'GXH': { city_zh: '夏河', name_zh: '甘南夏河机场' },
  'GYS': { city_zh: '广元', name_zh: '广元盘龙机场' },
  'DAX': { city_zh: '达州', name_zh: '达州金垭机场' },
  'KGT': { city_zh: '康定', name_zh: '康定机场' },
  'JZH': { city_zh: '九寨沟', name_zh: '九寨黄龙机场' },
  'AEB': { city_zh: '百色', name_zh: '百色巴马机场' },
  'ZUH': { city_zh: '珠海', name_zh: '珠海金湾机场' },
  'SWA': { city_zh: '揭阳', name_zh: '揭阳潮汕国际机场' },
  'MXZ': { city_zh: '梅县', name_zh: '梅县机场' },
  'ZHA': { city_zh: '湛江', name_zh: '湛江吴川机场' },
  'FUO': { city_zh: '佛山', name_zh: '佛山沙堤机场' },
  'HKG': { city_zh: '香港', name_zh: '香港国际机场' },
  'MFM': { city_zh: '澳门', name_zh: '澳门国际机场' },
  'TPE': { city_zh: '台北', name_zh: '台北桃园国际机场' },
  'KHH': { city_zh: '高雄', name_zh: '高雄小港国际机场' },
  'RMQ': { city_zh: '台中', name_zh: '台中清泉岗机场' },
  'HUN': { city_zh: '花莲', name_zh: '花莲机场' },
  'KNH': { city_zh: '金门', name_zh: '金门机场' },
  'MFK': { city_zh: '马祖', name_zh: '马祖北竿机场' },
  'KIX': { city_zh: '大阪', name_zh: '大阪关西国际机场' },
  'ITM': { city_zh: '大阪', name_zh: '大阪伊丹机场' },
  'NRT': { city_zh: '东京', name_zh: '东京成田国际机场' },
  'HND': { city_zh: '东京', name_zh: '东京羽田国际机场' },
  'CTS': { city_zh: '札幌', name_zh: '札幌新千岁机场' },
  'FUK': { city_zh: '福冈', name_zh: '福冈机场' },
  'OKA': { city_zh: '那霸', name_zh: '那霸机场' },
  'NGO': { city_zh: '名古屋', name_zh: '名古屋中部国际机场' },
  'HIJ': { city_zh: '广岛', name_zh: '广岛机场' },
  'SDJ': { city_zh: '仙台', name_zh: '仙台机场' },
  'KOJ': { city_zh: '鹿儿岛', name_zh: '鹿儿岛机场' },
  'KMJ': { city_zh: '熊本', name_zh: '熊本机场' },
  'NGS': { city_zh: '长崎', name_zh: '长崎机场' },
  'OIT': { city_zh: '大分', name_zh: '大分机场' },
  'MYJ': { city_zh: '松山', name_zh: '松山机场' },
  'TAK': { city_zh: '高松', name_zh: '高松机场' },
  'HIW': { city_zh: '广岛', name_zh: '广岛西城机场' },
  'AOJ': { city_zh: '青森', name_zh: '青森机场' },
  'AKJ': { city_zh: '旭川', name_zh: '旭川机场' },
  'OKJ': { city_zh: '冈山', name_zh: '冈山机场' },
  'FKS': { city_zh: '福岛', name_zh: '福岛机场' },
  'KMI': { city_zh: '宫崎', name_zh: '宫崎机场' },
  'TTJ': { city_zh: '鸟取', name_zh: '鸟取机场' },
  'IWJ': { city_zh: '石见', name_zh: '石见机场' },
  'OBO': { city_zh: '带广', name_zh: '带广机场' },
  'HSG': { city_zh: '佐贺', name_zh: '佐贺机场' },
  'SHM': { city_zh: '白滨', name_zh: '南纪白滨机场' },
  'OKI': { city_zh: '隐岐', name_zh: '隐岐机场' },
  'ICN': { city_zh: '首尔', name_zh: '首尔仁川国际机场' },
  'GMP': { city_zh: '首尔', name_zh: '首尔金浦国际机场' },
  'PUS': { city_zh: '釜山', name_zh: '釜山金海国际机场' },
  'CJU': { city_zh: '济州岛', name_zh: '济州国际机场' },
  'TAE': { city_zh: '大邱', name_zh: '大邱国际机场' },
  'CJJ': { city_zh: '清州', name_zh: '清州国际机场' },
  'KWJ': { city_zh: '光州', name_zh: '光州机场' },
  'RSU': { city_zh: '丽水', name_zh: '丽水机场' },
  'KPO': { city_zh: '浦项', name_zh: '浦项机场' },
  'BKK': { city_zh: '曼谷', name_zh: '曼谷素万那普国际机场' },
  'DMK': { city_zh: '曼谷', name_zh: '曼谷廊曼国际机场' },
  'KUL': { city_zh: '吉隆坡', name_zh: '吉隆坡国际机场' },
  'SZB': { city_zh: '吉隆坡', name_zh: '吉隆坡梳邦机场' },
  'PEN': { city_zh: '槟城', name_zh: '槟城国际机场' },
  'JHB': { city_zh: '新山', name_zh: '新山士乃国际机场' },
  'BKI': { city_zh: '哥打基纳巴卢(亚庇)', name_zh: '哥打基纳巴卢国际机场' },
  'KCH': { city_zh: '古晋', name_zh: '古晋国际机场' },
  'SDK': { city_zh: '山打根', name_zh: '山打根机场' },
  'TWU': { city_zh: '斗湖', name_zh: '斗湖机场' },
  'MYY': { city_zh: '美里', name_zh: '美里机场' },
  'TGG': { city_zh: '瓜拉登嘉楼', name_zh: '瓜拉登嘉楼机场' },
  'KBR': { city_zh: '哥打巴鲁', name_zh: '苏丹伊斯梅尔佩特拉机场' },
  'AOR': { city_zh: '亚罗士打', name_zh: '亚罗士打机场' },
  'SBW': { city_zh: '诗巫', name_zh: '诗巫机场' },
  'LGK': { city_zh: '兰卡威', name_zh: '兰卡威国际机场' },
  'IPH': { city_zh: '怡保', name_zh: '怡保机场' },
  'MKZ': { city_zh: '马六甲', name_zh: '马六甲机场' },
  'TOD': { city_zh: '刁曼岛', name_zh: '刁曼岛机场' },
  'RDN': { city_zh: '热浪岛', name_zh: '热浪岛机场' },
  'BWN': { city_zh: '斯里巴加湾市', name_zh: '文莱国际机场' },
  'LBU': { city_zh: '纳闽', name_zh: '纳闽机场' },
  'MNL': { city_zh: '马尼拉', name_zh: '马尼拉尼诺伊·阿基诺国际机场' },
  'CEB': { city_zh: '宿务', name_zh: '宿务麦克坦国际机场' },
  'DVO': { city_zh: '达沃', name_zh: '达沃国际机场' },
  'CRK': { city_zh: '克拉克', name_zh: '克拉克国际机场' },
  'ILO': { city_zh: '伊洛伊洛', name_zh: '伊洛伊洛国际机场' },
  'PPS': { city_zh: '公主港', name_zh: '公主港机场' },
  'CGY': { city_zh: '卡加延德奥罗', name_zh: '卡加延德奥罗机场' },
  'TAG': { city_zh: '塔比拉兰', name_zh: '塔比拉兰机场' },
  'GES': { city_zh: '桑托斯将军城', name_zh: '桑托斯将军城机场' },
  'BCD': { city_zh: '巴科洛德', name_zh: '巴科洛德机场' },
  'MPH': { city_zh: '卡提克兰', name_zh: '卡提克兰机场' },
  'ZAM': { city_zh: '三宝颜', name_zh: '三宝颜国际机场' },
  'TAC': { city_zh: '塔克洛班', name_zh: '丹尼尔·齐尔塞斯机场' },
  'CYP': { city_zh: '卡利博', name_zh: '卡利博国际机场' },
  'DGT': { city_zh: '杜马格特', name_zh: '杜马格特机场' },
  'BXU': { city_zh: '布土安', name_zh: '布土安机场' },
  'CGK': { city_zh: '雅加达', name_zh: '雅加达苏加诺-哈达国际机场' },
  'DPS': { city_zh: '巴厘岛', name_zh: '巴厘岛登巴萨国际机场' },
  'SUB': { city_zh: '泗水', name_zh: '泗水朱安达国际机场' },
  'KNO': { city_zh: '棉兰', name_zh: '棉兰瓜拉纳穆国际机场' },
  'UPG': { city_zh: '望加锡', name_zh: '望加锡苏丹哈桑丁国际机场' },
  'BPN': { city_zh: '巴厘巴板', name_zh: '巴厘巴板机场' },
  'BDJ': { city_zh: '马辰', name_zh: '马辰机场' },
  'JOG': { city_zh: '日惹', name_zh: '日惹国际机场' },
  'SOC': { city_zh: '梭罗', name_zh: '梭罗机场' },
  'PLM': { city_zh: '巨港', name_zh: '巨港苏丹马哈茂德·巴达鲁丁二世机场' },
  'PDG': { city_zh: '巴东', name_zh: '巴东机场' },
  'PKU': { city_zh: '北干巴鲁', name_zh: '北干巴鲁机场' },
  'BTH': { city_zh: '巴淡岛', name_zh: '巴淡岛机场' },
  'PNK': { city_zh: '坤甸', name_zh: '坤甸机场' },
  'AMQ': { city_zh: '安汶', name_zh: '安汶机场' },
  'MDC': { city_zh: '万鸦老', name_zh: '万鸦老机场' },
  'DJJ': { city_zh: '查亚普拉', name_zh: '查亚普拉机场' },
  'AMI': { city_zh: '马塔兰', name_zh: '龙目国际机场' },
  'BDO': { city_zh: '万隆', name_zh: '万隆机场' },
  'SRG': { city_zh: '三宝垄', name_zh: '三宝垄机场' },
  'TTE': { city_zh: '特尔纳特', name_zh: '特尔纳特机场' },
  'KDI': { city_zh: '肯达里', name_zh: '肯达里机场' },
  'TMC': { city_zh: '古邦', name_zh: '古邦机场' },
  'LBJ': { city_zh: '拉布汉巴乔', name_zh: '科莫多机场' },
  'TJQ': { city_zh: '丹戎潘丹', name_zh: '丹戎潘丹机场' },
  'PKY': { city_zh: '帕朗卡拉亚', name_zh: '帕朗卡拉亚机场' },
  'SGN': { city_zh: '胡志明市', name_zh: '胡志明市新山一国际机场' },
  'HAN': { city_zh: '河内', name_zh: '河内内排国际机场' },
  'DAD': { city_zh: '岘港', name_zh: '岘港国际机场' },
  'CXR': { city_zh: '芽庄', name_zh: '芽庄金兰国际机场' },
  'PQC': { city_zh: '富国', name_zh: '富国国际机场' },
  'VCA': { city_zh: '芹苴', name_zh: '芹苴机场' },
  'HPH': { city_zh: '海防', name_zh: '海防机场' },
  'HUI': { city_zh: '顺化', name_zh: '顺化机场' },
  'VCL': { city_zh: '归仁', name_zh: '归仁机场' },
  'DLI': { city_zh: '大叻', name_zh: '大叻机场' },
  'VKG': { city_zh: '迪石', name_zh: '迪石机场' },
  'VDO': { city_zh: '云屯', name_zh: '云屯国际机场' },
  'BKK': { city_zh: '曼谷', name_zh: '曼谷素万那普国际机场' },
  'DMK': { city_zh: '曼谷', name_zh: '曼谷廊曼国际机场' },
  'CNX': { city_zh: '清迈', name_zh: '清迈国际机场' },
  'CEI': { city_zh: '清莱', name_zh: '清莱国际机场' },
  'HKT': { city_zh: '普吉', name_zh: '普吉国际机场' },
  'USM': { city_zh: '苏梅岛', name_zh: '苏梅岛机场' },
  'KBV': { city_zh: '甲米', name_zh: '甲米机场' },
  'UTH': { city_zh: '乌隆他尼', name_zh: '乌隆他尼机场' },
  'UBP': { city_zh: '乌汶', name_zh: '乌汶机场' },
  'HDY': { city_zh: '合艾', name_zh: '合艾国际机场' },
  'TST': { city_zh: '董里', name_zh: '董里机场' },
  'PHS': { city_zh: '彭世洛', name_zh: '彭世洛机场' },
  'UTP': { city_zh: '芭堤雅', name_zh: '乌塔堡国际机场' },
  'REP': { city_zh: '暹粒', name_zh: '暹粒吴哥国际机场' },
  'PNH': { city_zh: '金边', name_zh: '金边国际机场' },
  'KOS': { city_zh: '西哈努克城', name_zh: '西哈努克国际机场' },
  'SAI': { city_zh: '暹粒', name_zh: '暹粒新机场' },
  'VTE': { city_zh: '万象', name_zh: '万象瓦岱国际机场' },
  'LPQ': { city_zh: '琅勃拉邦', name_zh: '琅勃拉邦国际机场' },
  'PKZ': { city_zh: '巴色', name_zh: '巴色国际机场' },
  'ODY': { city_zh: '乌多姆塞', name_zh: '乌多姆塞机场' },
  'ZVK': { city_zh: '沙湾拿吉', name_zh: '沙湾拿吉机场' },
  'RGN': { city_zh: '仰光', name_zh: '仰光国际机场' },
  'MDL': { city_zh: '曼德勒', name_zh: '曼德勒国际机场' },
  'NYU': { city_zh: '蒲甘', name_zh: '蒲甘机场' },
  'HEH': { city_zh: '东枝', name_zh: '东枝机场' },
  'SNW': { city_zh: '丹兑', name_zh: '丹兑机场' },
  'THL': { city_zh: '大其力', name_zh: '大其力机场' },
  'KYP': { city_zh: '实兑', name_zh: '实兑机场' },
  'MGZ': { city_zh: '丹老', name_zh: '丹老机场' },
  'NYT': { city_zh: '内比都', name_zh: '内比都机场' },
  'Suvarnabhumi Airport': { name_zh: '曼谷素万那普国际机场' },
  'Don Mueang International Airport': { name_zh: '曼谷廊曼国际机场' },
  'Kuala Lumpur International Airport': { name_zh: '吉隆坡国际机场' },
  'Subang Airport': { name_zh: '吉隆坡梳邦机场' },
  'Penang International Airport': { name_zh: '槟城国际机场' },
  'Senai International Airport': { name_zh: '新山士乃国际机场' },
  'Kota Kinabalu International Airport': { name_zh: '哥打基纳巴卢国际机场' },
  'Kuching International Airport': { name_zh: '古晋国际机场' },
  'Sandakan Airport': { name_zh: '山打根机场' },
  'Tawau Airport': { name_zh: '斗湖机场' },
  'Miri Airport': { name_zh: '美里机场' },
  'Langkawi International Airport': { name_zh: '兰卡威国际机场' },
  'Brunei International Airport': { name_zh: '文莱国际机场' },
  'Ninoy Aquino International Airport': { name_zh: '马尼拉尼诺伊·阿基诺国际机场' },
  'Mactan-Cebu International Airport': { name_zh: '宿务麦克坦国际机场' },
  'Francisco Bangoy International Airport': { name_zh: '达沃国际机场' },
  'Clark International Airport': { name_zh: '克拉克国际机场' },
  'Iloilo International Airport': { name_zh: '伊洛伊洛国际机场' },
  'Puerto Princesa Airport': { name_zh: '公主港机场' },
  'Soekarno-Hatta International Airport': { name_zh: '雅加达苏加诺-哈达国际机场' },
  'Ngurah Rai International Airport': { name_zh: '巴厘岛登巴萨国际机场' },
  'Juanda International Airport': { name_zh: '泗水朱安达国际机场' },
  'Kualanamu International Airport': { name_zh: '棉兰瓜拉纳穆国际机场' },
  'Sultan Hasanuddin International Airport': { name_zh: '望加锡苏丹哈桑丁国际机场' },
  'Sepinggan Airport': { name_zh: '巴厘巴板机场' },
  'Adisutjipto International Airport': { name_zh: '日惹国际机场' },
  'Sultan Mahmud Badaruddin II Airport': { name_zh: '巨港苏丹马哈茂德·巴达鲁丁二世机场' },
  'Minangkabau Airport': { name_zh: '巴东机场' },
  'Sultan Syarif Kasim II Airport': { name_zh: '北干巴鲁机场' },
  'Hang Nadim Airport': { name_zh: '巴淡岛机场' },
  'Supadio Airport': { name_zh: '坤甸机场' },
  'Sam Ratulangi Airport': { name_zh: '万鸦老机场' },
  'Lombok International Airport': { name_zh: '龙目国际机场' },
  'Husein Sastranegara International Airport': { name_zh: '万隆机场' },
  'Komodo Airport': { name_zh: '科莫多机场' },
  'Tan Son Nhat International Airport': { name_zh: '胡志明市新山一国际机场' },
  'Noi Bai International Airport': { name_zh: '河内内排国际机场' },
  'Da Nang International Airport': { name_zh: '岘港国际机场' },
  'Cam Ranh International Airport': { name_zh: '芽庄金兰国际机场' },
  'Phu Quoc International Airport': { name_zh: '富国国际机场' },
  'Can Tho Airport': { name_zh: '芹苴机场' },
  'Cat Bi International Airport': { name_zh: '海防机场' },
  'Phu Bai International Airport': { name_zh: '顺化机场' },
  'Van Don International Airport': { name_zh: '云屯国际机场' },
  'Suvarnabhumi Airport': { name_zh: '曼谷素万那普国际机场' },
  'Don Mueang International Airport': { name_zh: '曼谷廊曼国际机场' },
  'Chiang Mai International Airport': { name_zh: '清迈国际机场' },
  'Chiang Rai International Airport': { name_zh: '清莱国际机场' },
  'Phuket International Airport': { name_zh: '普吉国际机场' },
  'Samui Airport': { name_zh: '苏梅岛机场' },
  'Krabi Airport': { name_zh: '甲米机场' },
  'Udon Thani Airport': { name_zh: '乌隆他尼机场' },
  'Ubon Ratchathani Airport': { name_zh: '乌汶机场' },
  'Hat Yai International Airport': { name_zh: '合艾国际机场' },
  'U-Tapao International Airport': { name_zh: '芭堤雅乌塔堡国际机场' },
  'Siem Reap Angkor International Airport': { name_zh: '暹粒吴哥国际机场' },
  'Phnom Penh International Airport': { name_zh: '金边国际机场' },
  'Sihanouk International Airport': { name_zh: '西哈努克国际机场' },
  'Wattay International Airport': { name_zh: '万象瓦岱国际机场' },
  'Luang Prabang International Airport': { name_zh: '琅勃拉邦国际机场' },
  'Pakse International Airport': { name_zh: '巴色国际机场' },
  'Yangon International Airport': { name_zh: '仰光国际机场' },
  'Mandalay International Airport': { name_zh: '曼德勒国际机场' },
  'Bagan Airport': { name_zh: '蒲甘机场' },
  'Heho Airport': { name_zh: '东枝机场' },
  'Thandwe Airport': { name_zh: '丹兑机场' },
  'Naypyidaw Airport': { name_zh: '内比都机场' },
  'Tokyo Haneda Airport': { name_zh: '东京羽田国际机场' },
  'Tokyo Narita Airport': { name_zh: '东京成田国际机场' },
  'Osaka Kansai Airport': { name_zh: '大阪关西国际机场' },
  'Osaka International Airport': { name_zh: '大阪伊丹机场' },
  'Tokyo Narita Airport': { name_zh: '东京成田国际机场' },
  'Tokyo Haneda Airport': { name_zh: '东京羽田国际机场' },
  'New Chitose Airport': { name_zh: '札幌新千岁机场' },
  'Fukuoka Airport': { name_zh: '福冈机场' },
  'Naha Airport': { name_zh: '那霸机场' },
  'Chubu Centrair International Airport': { name_zh: '名古屋中部国际机场' },
  'Hiroshima Airport': { name_zh: '广岛机场' },
  'Sendai Airport': { name_zh: '仙台机场' },
  'Kagoshima Airport': { name_zh: '鹿儿岛机场' },
  'Kumamoto Airport': { name_zh: '熊本机场' },
  'Nagasaki Airport': { name_zh: '长崎机场' },
  'Oita Airport': { name_zh: '大分机场' },
  'Matsuyama Airport': { name_zh: '松山机场' },
  'Takamatsu Airport': { name_zh: '高松机场' },
  'Aomori Airport': { name_zh: '青森机场' },
  'Asahikawa Airport': { name_zh: '旭川机场' },
  'Okayama Airport': { name_zh: '冈山机场' },
  'Fukushima Airport': { name_zh: '福岛机场' },
  'Miyazaki Airport': { name_zh: '宫崎机场' },
  'Tottori Airport': { name_zh: '鸟取机场' },
  'Iwami Airport': { name_zh: '石见机场' },
  'Tokachi-Obihiro Airport': { name_zh: '带广机场' },
  'Saga Airport': { name_zh: '佐贺机场' },
  'Nanki Shirahama Airport': { name_zh: '南纪白滨机场' },
  'Oki Airport': { name_zh: '隐岐机场' },
  'Incheon International Airport': { name_zh: '首尔仁川国际机场' },
  'Gimpo International Airport': { name_zh: '首尔金浦国际机场' },
  'Gimhae International Airport': { name_zh: '釜山金海国际机场' },
  'Jeju International Airport': { name_zh: '济州国际机场' },
  'Daegu International Airport': { name_zh: '大邱国际机场' },
  'Cheongju International Airport': { name_zh: '清州国际机场' },
  'Gwangju Airport': { name_zh: '光州机场' },
  'Yeosu Airport': { name_zh: '丽水机场' },
  'Pohang Airport': { name_zh: '浦项机场' },
  'Singapore Changi Airport': { name_zh: '新加坡樟宜国际机场' },
  'Hong Kong International Airport': { name_zh: '香港国际机场' },
  'Taiwan Taoyuan International Airport': { name_zh: '台北桃园国际机场' },
  'Beijing Capital International Airport': { name_zh: '北京首都国际机场' },
  'Shanghai Pudong International Airport': { name_zh: '上海浦东国际机场' },
  'Shanghai Hongqiao International Airport': { name_zh: '上海虹桥国际机场' },
  'Guangzhou Baiyun International Airport': { name_zh: '广州白云国际机场' },
  'Shenzhen Baoan International Airport': { name_zh: '深圳宝安国际机场' },
  'Chengdu Shuangliu International Airport': { name_zh: '成都双流国际机场' },
  'Hangzhou Xiaoshan International Airport': { name_zh: '杭州萧山国际机场' },
  'Xian Xianyang International Airport': { name_zh: '西安咸阳国际机场' },
  'Nanjing Lukou International Airport': { name_zh: '南京禄口国际机场' },
  'Wuhan Tianhe International Airport': { name_zh: '武汉天河国际机场' },
  'Chongqing Jiangbei International Airport': { name_zh: '重庆江北国际机场' },
  'Kunming Changshui International Airport': { name_zh: '昆明长水国际机场' },
  
  // 欧洲
  'LHR': { city_zh: '伦敦', name_zh: '伦敦希思罗国际机场' },
  'LGW': { city_zh: '伦敦', name_zh: '伦敦盖特威克机场' },
  'CDG': { city_zh: '巴黎', name_zh: '巴黎戴高乐国际机场' },
  'ORY': { city_zh: '巴黎', name_zh: '巴黎奥利机场' },
  'FRA': { city_zh: '法兰克福', name_zh: '法兰克福国际机场' },
  'MUC': { city_zh: '慕尼黑', name_zh: '慕尼黑国际机场' },
  'AMS': { city_zh: '阿姆斯特丹', name_zh: '阿姆斯特丹史基浦机场' },
  'BRU': { city_zh: '布鲁塞尔', name_zh: '布鲁塞尔国际机场' },
  'ZRH': { city_zh: '苏黎世', name_zh: '苏黎世国际机场' },
  'GVA': { city_zh: '日内瓦', name_zh: '日内瓦国际机场' },
  'MAD': { city_zh: '马德里', name_zh: '马德里巴拉哈斯机场' },
  'BCN': { city_zh: '巴塞罗那', name_zh: '巴塞罗那埃尔普拉特机场' },
  'FCO': { city_zh: '罗马', name_zh: '罗马菲乌米奇诺机场' },
  'MXP': { city_zh: '米兰', name_zh: '米兰马尔彭萨机场' },
  'IST': { city_zh: '伊斯坦布尔', name_zh: '伊斯坦布尔国际机场' },
  'SAW': { city_zh: '伊斯坦布尔', name_zh: '伊斯坦布尔萨比哈格克琴国际机场' },
  'ESB': { city_zh: '安卡拉', name_zh: '安卡拉埃森博阿国际机场' },
  'ADB': { city_zh: '伊兹密尔', name_zh: '伊兹密尔阿德南曼德列斯国际机场' },
  'AYT': { city_zh: '安塔利亚', name_zh: '安塔利亚国际机场' },
  // 中东/海湾地区
  'DXB': { city_zh: '迪拜', name_zh: '迪拜国际机场' },
  'DWC': { city_zh: '迪拜', name_zh: '迪拜阿勒马克图姆国际机场' },
  'AUH': { city_zh: '阿布扎比', name_zh: '阿布扎比扎耶德国际机场' },
  'SHJ': { city_zh: '沙迦', name_zh: '沙迦国际机场' },
  'DOH': { city_zh: '多哈', name_zh: '多哈哈马德国际机场' },
  'BAH': { city_zh: '麦纳麦', name_zh: '巴林国际机场' },
  'KWI': { city_zh: '科威特城', name_zh: '科威特国际机场' },
  'MCT': { city_zh: '马斯喀特', name_zh: '马斯喀特国际机场' },
  'RUH': { city_zh: '利雅得', name_zh: '利雅得哈立德国王国际机场' },
  'JED': { city_zh: '吉达', name_zh: '吉达阿卜杜勒-阿齐兹国王国际机场' },
  'MED': { city_zh: '麦地那', name_zh: '麦地那穆罕默德·本·阿卜杜勒-阿齐兹亲王国际机场' },
  'DMM': { city_zh: '达曼', name_zh: '达曼法赫德国王国际机场' },
  'DHA': { city_zh: '达兰', name_zh: '达兰机场' },
  'TIF': { city_zh: '塔伊夫', name_zh: '塔伊夫国际机场' },
  'EAM': { city_zh: '奈季兰', name_zh: '奈季兰机场' },
  'AMM': { city_zh: '安曼', name_zh: '安曼阿莉亚王后国际机场' },
  'ADJ': { city_zh: '安曼', name_zh: '安曼马尔卡机场' },
  'AQJ': { city_zh: '亚喀巴', name_zh: '亚喀巴国际机场' },
  'BEY': { city_zh: '贝鲁特', name_zh: '贝鲁特拉菲克·哈里里国际机场' },
  'BGW': { city_zh: '巴格达', name_zh: '巴格达国际机场' },
  'BSR': { city_zh: '巴士拉', name_zh: '巴士拉国际机场' },
  'EBL': { city_zh: '埃尔比勒', name_zh: '埃尔比勒国际机场' },
  'NJF': { city_zh: '纳杰夫', name_zh: '纳杰夫国际机场' },
  'ISU': { city_zh: '苏莱曼尼亚', name_zh: '苏莱曼尼亚国际机场' },
  'THR': { city_zh: '德黑兰', name_zh: '德黑兰梅赫拉巴德国际机场' },
  'IKA': { city_zh: '德黑兰', name_zh: '德黑兰伊玛目霍梅尼国际机场' },
  'MHD': { city_zh: '马什哈德', name_zh: '马什哈德国际机场' },
  'IFN': { city_zh: '伊斯法罕', name_zh: '伊斯法罕国际机场' },
  'SYZ': { city_zh: '设拉子', name_zh: '设拉子国际机场' },
  'TBZ': { city_zh: '大不里士', name_zh: '大不里士国际机场' },
  'KIH': { city_zh: '基什岛', name_zh: '基什岛国际机场' },
  // 北非
  'CAI': { city_zh: '开罗', name_zh: '开罗国际机场' },
  'SPX': { city_zh: '开罗', name_zh: '开罗斯芬克斯国际机场' },
  'HRG': { city_zh: '赫尔格达', name_zh: '赫尔格达国际机场' },
  'SSH': { city_zh: '沙姆沙伊赫', name_zh: '沙姆沙伊赫国际机场' },
  'ASW': { city_zh: '阿斯旺', name_zh: '阿斯旺国际机场' },
  'HBE': { city_zh: '亚历山大', name_zh: '亚历山大博格埃尔阿拉伯国际机场' },
  'ALY': { city_zh: '亚历山大', name_zh: '亚历山大国际机场' },
  'LXR': { city_zh: '卢克索', name_zh: '卢克索国际机场' },
  'RMF': { city_zh: '马尔萨阿拉姆', name_zh: '马尔萨阿拉姆国际机场' },
  'TUN': { city_zh: '突尼斯', name_zh: '突尼斯迦太基国际机场' },
  'MIR': { city_zh: '莫纳斯提尔', name_zh: '莫纳斯提尔哈比卜·布尔吉巴国际机场' },
  'DJE': { city_zh: '杰尔巴', name_zh: '杰尔巴-杰尔吉斯国际机场' },
  'ALG': { city_zh: '阿尔及尔', name_zh: '阿尔及尔胡阿里·布迈丁机场' },
  'ORN': { city_zh: '奥兰', name_zh: '奥兰埃塞尼亚机场' },
  'CZL': { city_zh: '君士坦丁', name_zh: '君士坦丁穆罕默德·布迪亚夫机场' },
  'RAK': { city_zh: '马拉喀什', name_zh: '马拉喀什梅纳拉机场' },
  'CMN': { city_zh: '卡萨布兰卡', name_zh: '卡萨布兰卡穆罕默德五世国际机场' },
  'FEZ': { city_zh: '非斯', name_zh: '非斯萨伊斯机场' },
  'AGA': { city_zh: '阿加迪尔', name_zh: '阿加迪尔阿尔马西拉机场' },
  'RBA': { city_zh: '拉巴特', name_zh: '拉巴特萨累机场' },
  'TNG': { city_zh: '丹吉尔', name_zh: '丹吉尔伊本·巴图塔机场' },
  'OUD': { city_zh: '乌季达', name_zh: '乌季达安加兹机场' },
  'TET': { city_zh: '得土安', name_zh: '得土安萨尼亚拉梅尔机场' },
  'NDR': { city_zh: '纳祖尔', name_zh: '纳祖尔国际机场' },
  // 欧洲主要新增机场
  'VIE': { city_zh: '维也纳', name_zh: '维也纳国际机场' },
  'CPH': { city_zh: '哥本哈根', name_zh: '哥本哈根卡斯特鲁普机场' },
  'ARN': { city_zh: '斯德哥尔摩', name_zh: '斯德哥尔摩阿兰达机场' },
  'GOT': { city_zh: '哥德堡', name_zh: '哥德堡兰德维特机场' },
  'MMX': { city_zh: '马尔默', name_zh: '马尔默机场' },
  'OSL': { city_zh: '奥斯陆', name_zh: '奥斯陆加勒穆恩机场' },
  'BGO': { city_zh: '卑尔根', name_zh: '卑尔根弗莱斯兰机场' },
  'SVG': { city_zh: '斯塔万格', name_zh: '斯塔万格机场' },
  'TRD': { city_zh: '特隆赫姆', name_zh: '特隆赫姆韦尔内斯机场' },
  'TOS': { city_zh: '特罗姆瑟', name_zh: '特罗姆瑟机场' },
  'EVE': { city_zh: '纳尔维克', name_zh: '纳尔维克机场' },
  'HAU': { city_zh: '海于格松', name_zh: '海于格松机场' },
  'AES': { city_zh: '奥勒松', name_zh: '奥勒松机场' },
  'HEL': { city_zh: '赫尔辛基', name_zh: '赫尔辛基万塔机场' },
  'DUB': { city_zh: '都柏林', name_zh: '都柏林机场' },
  'ORK': { city_zh: '科克', name_zh: '科克机场' },
  'EDI': { city_zh: '爱丁堡', name_zh: '爱丁堡机场' },
  'MAN': { city_zh: '曼彻斯特', name_zh: '曼彻斯特机场' },
  'BHX': { city_zh: '伯明翰', name_zh: '伯明翰机场' },
  'BRS': { city_zh: '布里斯托尔', name_zh: '布里斯托尔机场' },
  'NCL': { city_zh: '纽卡斯尔', name_zh: '纽卡斯尔机场' },
  'GLA': { city_zh: '格拉斯哥', name_zh: '格拉斯哥机场' },
  'ABZ': { city_zh: '阿伯丁', name_zh: '阿伯丁国际机场' },
  'BFS': { city_zh: '贝尔法斯特', name_zh: '贝尔法斯特国际机场' },
  'DUS': { city_zh: '杜塞尔多夫', name_zh: '杜塞尔多夫机场' },
  'BER': { city_zh: '柏林', name_zh: '柏林勃兰登堡机场' },
  'TXL': { city_zh: '柏林', name_zh: '柏林泰格尔机场' },
  'HAM': { city_zh: '汉堡', name_zh: '汉堡机场' },
  'CGN': { city_zh: '科隆', name_zh: '科隆波恩机场' },
  'STR': { city_zh: '斯图加特', name_zh: '斯图加特机场' },
  'HAJ': { city_zh: '汉诺威', name_zh: '汉诺威机场' },
  'NUE': { city_zh: '纽伦堡', name_zh: '纽伦堡机场' },
  'DRS': { city_zh: '德累斯顿', name_zh: '德累斯顿机场' },
  'BRE': { city_zh: '不莱梅', name_zh: '不莱梅机场' },
  'LEJ': { city_zh: '莱比锡', name_zh: '莱比锡/哈雷机场' },
  'VCE': { city_zh: '威尼斯', name_zh: '威尼斯马可·波罗机场' },
  'BLQ': { city_zh: '博洛尼亚', name_zh: '博洛尼亚机场' },
  'NAP': { city_zh: '那不勒斯', name_zh: '那不勒斯国际机场' },
  'FLR': { city_zh: '佛罗伦萨', name_zh: '佛罗伦萨机场' },
  'CTA': { city_zh: '卡塔尼亚', name_zh: '卡塔尼亚丰塔纳罗萨机场' },
  'PMO': { city_zh: '巴勒莫', name_zh: '巴勒莫机场' },
  'BRI': { city_zh: '巴里', name_zh: '巴里卡罗·沃伊蒂瓦机场' },
  'TRN': { city_zh: '都灵', name_zh: '都灵机场' },
  'GOA': { city_zh: '热那亚', name_zh: '热那亚机场' },
  'VRN': { city_zh: '维罗纳', name_zh: '维罗纳机场' },
  'PSA': { city_zh: '比萨', name_zh: '比萨机场' },
  'CAG': { city_zh: '卡利亚里', name_zh: '卡利亚里机场' },
  'OLB': { city_zh: '奥尔比亚', name_zh: '奥尔比亚机场' },
  'ATH': { city_zh: '雅典', name_zh: '雅典埃莱夫塞里奥斯·韦尼泽洛斯国际机场' },
  'SKG': { city_zh: '塞萨洛尼基', name_zh: '塞萨洛尼基马其顿机场' },
  'HER': { city_zh: '伊拉克利翁', name_zh: '伊拉克利翁国际机场' },
  'RHO': { city_zh: '罗德岛', name_zh: '罗德岛国际机场' },
  'JMK': { city_zh: '米科诺斯', name_zh: '米科诺斯机场' },
  'JTR': { city_zh: '圣托里尼', name_zh: '圣托里尼机场' },
  'CFU': { city_zh: '科孚', name_zh: '科孚国际机场' },
  'LIS': { city_zh: '里斯本', name_zh: '里斯本波尔特拉机场' },
  'OPO': { city_zh: '波尔图', name_zh: '波尔图机场' },
  'FNC': { city_zh: '丰沙尔', name_zh: '丰沙尔马德拉机场' },
  'PDL': { city_zh: '蓬塔德尔加达', name_zh: '蓬塔德尔加达机场' },
  'WAW': { city_zh: '华沙', name_zh: '华沙肖邦机场' },
  'KRK': { city_zh: '克拉科夫', name_zh: '克拉科夫约翰·保罗二世机场' },
  'GDN': { city_zh: '格但斯克', name_zh: '格但斯克机场' },
  'WRO': { city_zh: '弗罗茨瓦夫', name_zh: '弗罗茨瓦夫机场' },
  'POZ': { city_zh: '波兹南', name_zh: '波兹南机场' },
  'KTW': { city_zh: '卡托维兹', name_zh: '卡托维兹机场' },
  'PRG': { city_zh: '布拉格', name_zh: '布拉格瓦茨拉夫·哈维尔机场' },
  'BUD': { city_zh: '布达佩斯', name_zh: '布达佩斯费伦茨·李斯特国际机场' },
  'BTS': { city_zh: '布拉迪斯拉发', name_zh: '布拉迪斯拉发机场' },
  'OTP': { city_zh: '布加勒斯特', name_zh: '布加勒斯特亨利·科安达国际机场' },
  'CLJ': { city_zh: '克卢日-纳波卡', name_zh: '克卢日-纳波卡国际机场' },
  'SOF': { city_zh: '索菲亚', name_zh: '索菲亚机场' },
  'SKP': { city_zh: '斯科普里', name_zh: '斯科普里亚历山大国际机场' },
  'TGD': { city_zh: '波德戈里察', name_zh: '波德戈里察机场' },
  'TIV': { city_zh: '蒂瓦特', name_zh: '蒂瓦特机场' },
  'BEG': { city_zh: '贝尔格莱德', name_zh: '贝尔格莱德尼古拉·特斯拉机场' },
  'ZAG': { city_zh: '萨格勒布', name_zh: '萨格勒布机场' },
  'SPU': { city_zh: '斯普利特', name_zh: '斯普利特机场' },
  'DBV': { city_zh: '杜布罗夫尼克', name_zh: '杜布罗夫尼克机场' },
  'LJU': { city_zh: '卢布尔雅那', name_zh: '卢布尔雅那机场' },
  'SJJ': { city_zh: '萨拉热窝', name_zh: '萨拉热窝国际机场' },
  'TIA': { city_zh: '地拉那', name_zh: '地拉那特蕾莎修女国际机场' },
  // 俄罗斯主要机场
  'SVO': { city_zh: '莫斯科', name_zh: '莫斯科谢列梅捷沃国际机场' },
  'DME': { city_zh: '莫斯科', name_zh: '莫斯科多莫杰多沃国际机场' },
  'VKO': { city_zh: '莫斯科', name_zh: '莫斯科伏努科沃国际机场' },
  'LED': { city_zh: '圣彼得堡', name_zh: '圣彼得堡普尔科沃机场' },
  'KZN': { city_zh: '喀山', name_zh: '喀山国际机场' },
  'ROV': { city_zh: '顿河畔罗斯托夫', name_zh: '顿河畔罗斯托夫普拉托夫国际机场' },
  'AER': { city_zh: '索契', name_zh: '索契国际机场' },
  'VVO': { city_zh: '符拉迪沃斯托克(海参崴)', name_zh: '符拉迪沃斯托克国际机场' },
  'KRR': { city_zh: '克拉斯诺达尔', name_zh: '克拉斯诺达尔国际机场' },
  'UFA': { city_zh: '乌法', name_zh: '乌法国际机场' },
  'OVB': { city_zh: '新西伯利亚', name_zh: '新西伯利亚托尔马切沃机场' },
  'SVX': { city_zh: '叶卡捷琳堡', name_zh: '叶卡捷琳堡科利佐沃机场' },
  // 印度
  'DEL': { city_zh: '新德里', name_zh: '新德里英迪拉·甘地国际机场' },
  'BOM': { city_zh: '孟买', name_zh: '孟买贾特拉帕蒂·希瓦吉国际机场' },
  'BLR': { city_zh: '班加罗尔', name_zh: '班加罗尔Kempegowda国际机场' },
  'MAA': { city_zh: '金奈', name_zh: '金奈国际机场' },
  'CCU': { city_zh: '加尔各答', name_zh: '加尔各答内塔吉·苏巴斯·钱德拉·鲍斯国际机场' },
  'HYD': { city_zh: '海德拉巴', name_zh: '海德拉巴拉吉夫·甘地国际机场' },
  'AMD': { city_zh: '艾哈迈达巴德', name_zh: '艾哈迈达巴德萨达尔·瓦拉巴伊·帕特尔国际机场' },
  'GOI': { city_zh: '果阿', name_zh: '果阿国际机场' },
  'COK': { city_zh: '科钦', name_zh: '科钦国际机场' },
  'PNQ': { city_zh: '浦那', name_zh: '浦那机场' },
  'GAU': { city_zh: '古瓦哈提', name_zh: '古瓦哈提洛普里纳特国际机场' },
  'LKO': { city_zh: '勒克瑙', name_zh: '勒克瑙乔杜里查兰·辛格国际机场' },
  'JAI': { city_zh: '斋浦尔', name_zh: '斋浦尔国际机场' },
  'VNS': { city_zh: '瓦拉纳西', name_zh: '瓦拉纳西机场' },
  'IXC': { city_zh: '昌迪加尔', name_zh: '昌迪加尔机场' },
  'NAG': { city_zh: '那格浦尔', name_zh: '那格浦尔机场' },
  'VGA': { city_zh: '维杰亚瓦达', name_zh: '维杰亚瓦达机场' },
  'IXM': { city_zh: '马杜赖', name_zh: '马杜赖机场' },
  'TRV': { city_zh: '特里凡得琅', name_zh: '特里凡得琅国际机场' },
  'VTZ': { city_zh: '维沙卡帕特南', name_zh: '维沙卡帕特南机场' },
  'IXB': { city_zh: '巴多格拉', name_zh: '巴多格拉机场' },
  'IXR': { city_zh: '兰契', name_zh: '兰契机场' },
  'PAT': { city_zh: '巴特那', name_zh: '巴特那机场' },
  'SXR': { city_zh: '斯利那加', name_zh: '斯利那加机场' },
  'IXL': { city_zh: '列城', name_zh: '列城机场' },
  'JDH': { city_zh: '焦特布尔', name_zh: '焦特布尔机场' },
  'UDR': { city_zh: '乌代布尔', name_zh: '乌代布尔机场' },
  'AGR': { city_zh: '阿格拉', name_zh: '阿格拉机场' },
  'IXZ': { city_zh: '布莱尔港', name_zh: '布莱尔港机场' },
  // 中亚
  'TSE': { city_zh: '阿斯塔纳', name_zh: '阿斯塔纳努尔苏丹·纳扎尔巴耶夫国际机场' },
  'ALA': { city_zh: '阿拉木图', name_zh: '阿拉木图国际机场' },
  'SCO': { city_zh: '阿克套', name_zh: '阿克套国际机场' },
  'UKK': { city_zh: '厄斯克门', name_zh: '厄斯克门机场' },
  'PWQ': { city_zh: '巴甫洛达尔', name_zh: '巴甫洛达尔机场' },
  'KVD': { city_zh: '占贾', name_zh: '占贾国际机场' },
  'GYD': { city_zh: '巴库', name_zh: '巴库盖达尔·阿利耶夫国际机场' },
  'EVN': { city_zh: '埃里温', name_zh: '埃里温兹瓦尔特诺茨国际机场' },
  'TBS': { city_zh: '第比利斯', name_zh: '第比利斯国际机场' },
  'KBP': { city_zh: '基辅', name_zh: '基辅鲍里斯波尔国际机场' },
  'ODS': { city_zh: '敖德萨', name_zh: '敖德萨国际机场' },
  'RZN': { city_zh: '梁赞', name_zh: '梁赞机场' },
  // 中亚五国
  'DYU': { city_zh: '杜尚别', name_zh: '杜尚别国际机场' },
  'TAS': { city_zh: '塔什干', name_zh: '塔什干国际机场' },
  'SKD': { city_zh: '撒马尔罕', name_zh: '撒马尔罕国际机场' },
  'BHK': { city_zh: '布哈拉', name_zh: '布哈拉国际机场' },
  'NMA': { city_zh: '纳曼干', name_zh: '纳曼干机场' },
  'FEG': { city_zh: '费尔干纳', name_zh: '费尔干纳机场' },
  'UGC': { city_zh: '乌尔根奇', name_zh: '乌尔根奇机场' },
  'NCU': { city_zh: '努库斯', name_zh: '努库斯机场' },
  'FRU': { city_zh: '比什凯克', name_zh: '比什凯克玛纳斯国际机场' },
  'OSS': { city_zh: '奥什', name_zh: '奥什机场' },
  'ASB': { city_zh: '阿什哈巴德', name_zh: '阿什哈巴德机场' },
  'CRZ': { city_zh: '土库曼纳巴德', name_zh: '土库曼纳巴德机场' },
  // 南亚
  'KTM': { city_zh: '加德满都', name_zh: '加德满都特里布万国际机场' },
  'PKR': { city_zh: '博卡拉', name_zh: '博卡拉机场' },
  'BWA': { city_zh: '蓝毗尼', name_zh: '蓝毗尼机场' },
  'MLE': { city_zh: '马累', name_zh: '马累维拉纳国际机场' },
  'CMB': { city_zh: '科伦坡', name_zh: '科伦坡班达拉奈克国际机场' },
  'RML': { city_zh: '科伦坡', name_zh: '科伦坡拉特马拉纳机场' },
  'DAC': { city_zh: '达卡', name_zh: '达卡沙阿贾拉勒国际机场' },
  'CGP': { city_zh: '吉大港', name_zh: '吉大港沙赫阿马纳国际机场' },
  'ZYL': { city_zh: '锡尔赫特', name_zh: '锡尔赫特机场' },
  'RJH': { city_zh: '拉杰沙希', name_zh: '拉杰沙希机场' },
  'ISB': { city_zh: '伊斯兰堡', name_zh: '伊斯兰堡国际机场' },
  'KHI': { city_zh: '卡拉奇', name_zh: '卡拉奇真纳国际机场' },
  'LHE': { city_zh: '拉合尔', name_zh: '拉合尔阿拉马·伊克巴勒国际机场' },
  'PEW': { city_zh: '白沙瓦', name_zh: '白沙瓦国际机场' },
  'SKT': { city_zh: '锡亚尔科特', name_zh: '锡亚尔科特国际机场' },
  'FSD': { city_zh: '费萨拉巴德', name_zh: '费萨拉巴德机场' },
  'MUX': { city_zh: '木尔坦', name_zh: '木尔坦国际机场' },
  // 非洲
  'ADD': { city_zh: '亚的斯亚贝巴', name_zh: '亚的斯亚贝巴博莱国际机场' },
  'NBO': { city_zh: '内罗毕', name_zh: '内罗毕乔莫·肯雅塔国际机场' },
  'MBA': { city_zh: '蒙巴萨', name_zh: '蒙巴萨莫伊国际机场' },
  'DAR': { city_zh: '达累斯萨拉姆', name_zh: '达累斯萨拉姆朱利叶斯·尼雷尔国际机场' },
  'ZNZ': { city_zh: '桑给巴尔', name_zh: '桑给巴尔阿贝德·阿马尼·卡鲁姆国际机场' },
  'EBB': { city_zh: '恩德培', name_zh: '恩德培国际机场' },
  'KGL': { city_zh: '基加利', name_zh: '基加利国际机场' },
  'HRE': { city_zh: '哈拉雷', name_zh: '哈拉雷国际机场' },
  'BUQ': { city_zh: '布拉瓦约', name_zh: '布拉瓦约机场' },
  'LUN': { city_zh: '卢萨卡', name_zh: '卢萨卡肯尼思·卡翁达国际机场' },
  'RRG': { city_zh: '毛里求斯', name_zh: '毛里求斯西沃萨古尔·拉姆古兰国际机场' },
  'MRU': { city_zh: '毛里求斯', name_zh: '毛里求斯西沃萨古尔·拉姆古兰国际机场' },
  'SEZ': { city_zh: '维多利亚', name_zh: '塞舌尔国际机场' },
  'TNR': { city_zh: '塔那那利佛', name_zh: '塔那那利佛伊瓦图国际机场' },
  'LOS': { city_zh: '拉各斯', name_zh: '拉各斯穆尔塔拉·穆罕默德国际机场' },
  'ABV': { city_zh: '阿布贾', name_zh: '阿布贾纳姆迪·阿齐基韦国际机场' },
  'KAN': { city_zh: '卡诺', name_zh: '卡诺马兰·阿明·卡诺国际机场' },
  'PHC': { city_zh: '哈科特港', name_zh: '哈科特港国际机场' },
  'ACC': { city_zh: '阿克拉', name_zh: '阿克拉科托卡国际机场' },
  'ABJ': { city_zh: '阿比让', name_zh: '阿比让费利克斯·乌弗埃-博瓦尼国际机场' },
  'DKR': { city_zh: '达喀尔', name_zh: '达喀尔布莱斯·狄亚尼国际机场' },
  'CMN': { city_zh: '卡萨布兰卡', name_zh: '卡萨布兰卡穆罕默德五世国际机场' },
  'RAK': { city_zh: '马拉喀什', name_zh: '马拉喀什梅纳拉机场' },
  'FEZ': { city_zh: '非斯', name_zh: '非斯萨伊斯机场' },
  'AGA': { city_zh: '阿加迪尔', name_zh: '阿加迪尔阿尔马西拉机场' },
  'RBA': { city_zh: '拉巴特', name_zh: '拉巴特萨累机场' },
  'TNG': { city_zh: '丹吉尔', name_zh: '丹吉尔伊本·巴图塔机场' },
  'CMN': { city_zh: '卡萨布兰卡', name_zh: '卡萨布兰卡穆罕默德五世国际机场' },
  'ALG': { city_zh: '阿尔及尔', name_zh: '阿尔及尔胡阿里·布迈丁机场' },
  'ORN': { city_zh: '奥兰', name_zh: '奥兰埃塞尼亚机场' },
  'TUN': { city_zh: '突尼斯', name_zh: '突尼斯迦太基国际机场' },
  'MIR': { city_zh: '莫纳斯提尔', name_zh: '莫纳斯提尔哈比卜·布尔吉巴国际机场' },
  'CAI': { city_zh: '开罗', name_zh: '开罗国际机场' },
  'HRG': { city_zh: '赫尔格达', name_zh: '赫尔格达国际机场' },
  'SSH': { city_zh: '沙姆沙伊赫', name_zh: '沙姆沙伊赫国际机场' },
  'JNB': { city_zh: '约翰内斯堡', name_zh: '约翰内斯堡奥坦博国际机场' },
  'CPT': { city_zh: '开普敦', name_zh: '开普敦国际机场' },
  'DUR': { city_zh: '德班', name_zh: '德班沙卡国王国际机场' },
  'PLZ': { city_zh: '伊丽莎白港', name_zh: '伊丽莎白港机场' },
  'GRJ': { city_zh: '乔治', name_zh: '乔治机场' },
  'KWI': { city_zh: '科威特城', name_zh: '科威特国际机场' },
  'BAH': { city_zh: '麦纳麦', name_zh: '巴林国际机场' },
  // 南美
  'GRU': { city_zh: '圣保罗', name_zh: '圣保罗瓜鲁柳斯国际机场' },
  'CGH': { city_zh: '圣保罗', name_zh: '圣保罗孔戈尼亚斯机场' },
  'GIG': { city_zh: '里约热内卢', name_zh: '里约热内卢加利昂国际机场' },
  'SDU': { city_zh: '里约热内卢', name_zh: '里约热内卢桑托斯杜蒙特机场' },
  'BSB': { city_zh: '巴西利亚', name_zh: '巴西利亚儒塞利诺·库比契克国际机场' },
  'CNF': { city_zh: '贝洛奥里藏特', name_zh: '贝洛奥里藏特坦克雷多·内维斯国际机场' },
  'SSA': { city_zh: '萨尔瓦多', name_zh: '萨尔瓦多德putado·路易斯·爱德华多·马加良斯机场' },
  'REC': { city_zh: '累西腓', name_zh: '累西腓瓜拉拉佩斯-吉尔贝托·弗雷雷国际机场' },
  'FOR': { city_zh: '福塔雷萨', name_zh: '福塔雷萨平托·马丁斯国际机场' },
  'POA': { city_zh: '阿雷格里港', name_zh: '阿雷格里港萨尔加多·菲略国际机场' },
  'CWB': { city_zh: '库里奇巴', name_zh: '库里奇巴阿丰索·佩纳国际机场' },
  'FLN': { city_zh: '弗洛里亚诺波利斯', name_zh: '弗洛里亚诺波利斯埃尔西利奥·卢兹国际机场' },
  'MAO': { city_zh: '马瑙斯', name_zh: '马瑙斯爱德华多·戈梅斯国际机场' },
  'BEL': { city_zh: '贝伦', name_zh: '贝伦瓦尔德坎斯国际机场' },
  'VCP': { city_zh: '坎皮纳斯', name_zh: '坎皮纳斯维拉科波斯国际机场' },
  'EZE': { city_zh: '布宜诺斯艾利斯', name_zh: '布宜诺斯艾利斯埃塞萨国际机场' },
  'AEP': { city_zh: '布宜诺斯艾利斯', name_zh: '布宜诺斯艾利斯豪尔赫·纽伯里机场' },
  'COR': { city_zh: '科尔多瓦', name_zh: '科尔多瓦英格尼尔·阿mbrosio·塔尔韦拉机场' },
  'MDZ': { city_zh: '门多萨', name_zh: '门多萨总督弗朗西斯科·加布里埃利国际机场' },
  'IGR': { city_zh: '伊瓜苏港', name_zh: '伊瓜苏港卡塔拉塔斯机场' },
  'SCL': { city_zh: '圣地亚哥', name_zh: '圣地亚哥阿图罗·梅里诺·贝尼特斯国际机场' },
  'LIM': { city_zh: '利马', name_zh: '利马豪尔赫·查韦斯国际机场' },
  'CUZ': { city_zh: '库斯科', name_zh: '库斯科亚历杭德罗·贝拉斯科·阿斯特特国际机场' },
  'BOG': { city_zh: '波哥大', name_zh: '波哥大埃尔多拉多国际机场' },
  'MDE': { city_zh: '麦德林', name_zh: '麦德林何塞·玛丽亚·科尔多瓦国际机场' },
  'CLO': { city_zh: '卡利', name_zh: '卡利阿方索·博尼利亚·阿拉贡国际机场' },
  'CTG': { city_zh: '卡塔赫纳', name_zh: '卡塔赫纳拉斐尔·努涅斯国际机场' },
  'BAQ': { city_zh: '巴兰基亚', name_zh: '巴兰基亚埃内斯托·科蒂斯机场' },
  'UIO': { city_zh: '基多', name_zh: '基多马里斯卡尔·苏克雷国际机场' },
  'GYE': { city_zh: '瓜亚基尔', name_zh: '瓜亚基尔何塞·华金·德·奥尔梅多国际机场' },
  'CCS': { city_zh: '加拉加斯', name_zh: '加拉加斯西蒙·玻利瓦尔国际机场' },
  'MVD': { city_zh: '蒙得维的亚', name_zh: '蒙得维的亚卡拉斯科国际机场' },
  'ASU': { city_zh: '亚松森', name_zh: '亚松森西尔维奥·佩蒂罗西国际机场' },
  'LPB': { city_zh: '拉巴斯', name_zh: '拉巴斯埃尔阿尔托国际机场' },
  'VVI': { city_zh: '圣克鲁斯', name_zh: '圣克鲁斯维鲁维鲁国际机场' },
  'UIB': { city_zh: '基布多', name_zh: '基布多机场' },
  'London Heathrow Airport': { name_zh: '伦敦希思罗国际机场' },
  'London Gatwick Airport': { name_zh: '伦敦盖特威克机场' },
  'Paris Charles de Gaulle Airport': { name_zh: '巴黎戴高乐国际机场' },
  'Paris Orly Airport': { name_zh: '巴黎奥利机场' },
  'Frankfurt am Main Airport': { name_zh: '法兰克福国际机场' },
  'Munich Airport': { name_zh: '慕尼黑国际机场' },
  'Amsterdam Airport Schiphol': { name_zh: '阿姆斯特丹史基浦机场' },
  'Brussels Airport': { name_zh: '布鲁塞尔国际机场' },
  'Zurich Airport': { name_zh: '苏黎世国际机场' },
  'Geneva Airport': { name_zh: '日内瓦国际机场' },
  'Madrid Barajas Airport': { name_zh: '马德里巴拉哈斯机场' },
  'Barcelona El Prat Airport': { name_zh: '巴塞罗那埃尔普拉特机场' },
  'Rome Fiumicino Airport': { name_zh: '罗马菲乌米奇诺机场' },
  'Milan Malpensa Airport': { name_zh: '米兰马尔彭萨机场' },
  'Istanbul Airport': { name_zh: '伊斯坦布尔国际机场' },
  'Sabiha Gokcen International Airport': { name_zh: '伊斯坦布尔萨比哈格克琴国际机场' },
  'Esenboga International Airport': { name_zh: '安卡拉埃森博阿国际机场' },
  'Adnan Menderes Airport': { name_zh: '伊兹密尔阿德南曼德列斯国际机场' },
  'Antalya Airport': { name_zh: '安塔利亚国际机场' },
  'Dubai International Airport': { name_zh: '迪拜国际机场' },
  'Al Maktoum International Airport': { name_zh: '迪拜阿勒马克图姆国际机场' },
  'Zayed International Airport': { name_zh: '阿布扎比扎耶德国际机场' },
  'Sharjah International Airport': { name_zh: '沙迦国际机场' },
  'Hamad International Airport': { name_zh: '多哈哈马德国际机场' },
  'Bahrain International Airport': { name_zh: '巴林国际机场' },
  'Kuwait International Airport': { name_zh: '科威特国际机场' },
  'Muscat International Airport': { name_zh: '马斯喀特国际机场' },
  'King Khalid International Airport': { name_zh: '利雅得哈立德国王国际机场' },
  'King Abdulaziz International Airport': { name_zh: '吉达阿卜杜勒-阿齐兹国王国际机场' },
  'Prince Mohammad bin Abdulaziz International Airport': { name_zh: '麦地那穆罕默德·本·阿卜杜勒-阿齐兹亲王国际机场' },
  'King Fahd International Airport': { name_zh: '达曼法赫德国王国际机场' },
  'Queen Alia International Airport': { name_zh: '安曼阿莉亚王后国际机场' },
  'Rafic Hariri International Airport': { name_zh: '贝鲁特拉菲克·哈里里国际机场' },
  'Baghdad International Airport': { name_zh: '巴格达国际机场' },
  'Basra International Airport': { name_zh: '巴士拉国际机场' },
  'Erbil International Airport': { name_zh: '埃尔比勒国际机场' },
  'Imam Khomeini International Airport': { name_zh: '德黑兰伊玛目霍梅尼国际机场' },
  'Mehrabad International Airport': { name_zh: '德黑兰梅赫拉巴德国际机场' },
  'Mashhad International Airport': { name_zh: '马什哈德国际机场' },
  'Isfahan International Airport': { name_zh: '伊斯法罕国际机场' },
  'Shiraz International Airport': { name_zh: '设拉子国际机场' },
  'Tabriz International Airport': { name_zh: '大不里士国际机场' },
  'Kish International Airport': { name_zh: '基什岛国际机场' },
  'Cairo International Airport': { name_zh: '开罗国际机场' },
  'Sphinx International Airport': { name_zh: '开罗斯芬克斯国际机场' },
  'Hurghada International Airport': { name_zh: '赫尔格达国际机场' },
  'Sharm el-Sheikh International Airport': { name_zh: '沙姆沙伊赫国际机场' },
  'Aswan International Airport': { name_zh: '阿斯旺国际机场' },
  'Borg El Arab International Airport': { name_zh: '亚历山大博格埃尔阿拉伯国际机场' },
  'Luxor International Airport': { name_zh: '卢克索国际机场' },
  'Marsa Alam International Airport': { name_zh: '马尔萨阿拉姆国际机场' },
  'Tunis Carthage International Airport': { name_zh: '突尼斯迦太基国际机场' },
  'Monastir Habib Bourguiba International Airport': { name_zh: '莫纳斯提尔哈比卜·布尔吉巴国际机场' },
  'Djerba-Zarzis International Airport': { name_zh: '杰尔巴-杰尔吉斯国际机场' },
  'Houari Boumediene Airport': { name_zh: '阿尔及尔胡阿里·布迈丁机场' },
  'Es Senia Airport': { name_zh: '奥兰埃塞尼亚机场' },
  'Mohamed Boudiaf International Airport': { name_zh: '君士坦丁穆罕默德·布迪亚夫机场' },
  'Menara Airport': { name_zh: '马拉喀什梅纳拉机场' },
  'Mohammed V International Airport': { name_zh: '卡萨布兰卡穆罕默德五世国际机场' },
  'Fes-Saiss Airport': { name_zh: '非斯萨伊斯机场' },
  'Al Massira Airport': { name_zh: '阿加迪尔阿尔马西拉机场' },
  'Rabat-Sale Airport': { name_zh: '拉巴特萨累机场' },
  'Ibn Battouta Airport': { name_zh: '丹吉尔伊本·巴图塔机场' },
  'Vienna International Airport': { name_zh: '维也纳国际机场' },
  'Copenhagen Airport': { name_zh: '哥本哈根卡斯特鲁普机场' },
  'Stockholm Arlanda Airport': { name_zh: '斯德哥尔摩阿兰达机场' },
  'Gothenburg Landvetter Airport': { name_zh: '哥德堡兰德维特机场' },
  'Malmo Airport': { name_zh: '马尔默机场' },
  'Oslo Gardermoen Airport': { name_zh: '奥斯陆加勒穆恩机场' },
  'Bergen Flesland Airport': { name_zh: '卑尔根弗莱斯兰机场' },
  'Stavanger Airport': { name_zh: '斯塔万格机场' },
  'Trondheim Vaernes Airport': { name_zh: '特隆赫姆韦尔内斯机场' },
  'Tromso Airport': { name_zh: '特罗姆瑟机场' },
  'Helsinki Vantaa Airport': { name_zh: '赫尔辛基万塔机场' },
  'Dublin Airport': { name_zh: '都柏林机场' },
  'Edinburgh Airport': { name_zh: '爱丁堡机场' },
  'Manchester Airport': { name_zh: '曼彻斯特机场' },
  'Birmingham Airport': { name_zh: '伯明翰机场' },
  'Berlin Brandenburg Airport': { name_zh: '柏林勃兰登堡机场' },
  'Hamburg Airport': { name_zh: '汉堡机场' },
  'Cologne Bonn Airport': { name_zh: '科隆波恩机场' },
  'Stuttgart Airport': { name_zh: '斯图加特机场' },
  'Hanover Airport': { name_zh: '汉诺威机场' },
  'Venice Marco Polo Airport': { name_zh: '威尼斯马可·波罗机场' },
  'Naples International Airport': { name_zh: '那不勒斯国际机场' },
  'Florence Airport': { name_zh: '佛罗伦萨机场' },
  'Catania Fontanarossa Airport': { name_zh: '卡塔尼亚丰塔纳罗萨机场' },
  'Palermo Airport': { name_zh: '巴勒莫机场' },
  'Bari Karol Wojtyla Airport': { name_zh: '巴里卡罗·沃伊蒂瓦机场' },
  'Turin Airport': { name_zh: '都灵机场' },
  'Genoa Airport': { name_zh: '热那亚机场' },
  'Verona Airport': { name_zh: '维罗纳机场' },
  'Pisa Airport': { name_zh: '比萨机场' },
  'Cagliari Airport': { name_zh: '卡利亚里机场' },
  'Olbia Airport': { name_zh: '奥尔比亚机场' },
  'Athens Eleftherios Venizelos International Airport': { name_zh: '雅典埃莱夫塞里奥斯·韦尼泽洛斯国际机场' },
  'Thessaloniki Macedonia Airport': { name_zh: '塞萨洛尼基马其顿机场' },
  'Heraklion International Airport': { name_zh: '伊拉克利翁国际机场' },
  'Rhodes International Airport': { name_zh: '罗德岛国际机场' },
  'Mykonos Airport': { name_zh: '米科诺斯机场' },
  'Santorini Airport': { name_zh: '圣托里尼机场' },
  'Corfu International Airport': { name_zh: '科孚国际机场' },
  'Lisbon Portela Airport': { name_zh: '里斯本波尔特拉机场' },
  'Porto Airport': { name_zh: '波尔图机场' },
  'Madeira Airport': { name_zh: '丰沙尔马德拉机场' },
  'Warsaw Chopin Airport': { name_zh: '华沙肖邦机场' },
  'Krakow John Paul II Airport': { name_zh: '克拉科夫约翰·保罗二世机场' },
  'Gdansk Airport': { name_zh: '格但斯克机场' },
  'Wroclaw Airport': { name_zh: '弗罗茨瓦夫机场' },
  'Poznan Airport': { name_zh: '波兹南机场' },
  'Katowice Airport': { name_zh: '卡托维兹机场' },
  'Prague Vaclav Havel Airport': { name_zh: '布拉格瓦茨拉夫·哈维尔机场' },
  'Budapest Ferenc Liszt International Airport': { name_zh: '布达佩斯费伦茨·李斯特国际机场' },
  'Bucharest Henri Coanda International Airport': { name_zh: '布加勒斯特亨利·科安达国际机场' },
  'Sofia Airport': { name_zh: '索菲亚机场' },
  'Belgrade Nikola Tesla Airport': { name_zh: '贝尔格莱德尼古拉·特斯拉机场' },
  'Zagreb Airport': { name_zh: '萨格勒布机场' },
  'Split Airport': { name_zh: '斯普利特机场' },
  'Dubrovnik Airport': { name_zh: '杜布罗夫尼克机场' },
  'Ljubljana Airport': { name_zh: '卢布尔雅那机场' },
  'Sarajevo International Airport': { name_zh: '萨拉热窝国际机场' },
  'Tirana Mother Teresa International Airport': { name_zh: '地拉那特蕾莎修女国际机场' },
  'Sheremetyevo International Airport': { name_zh: '莫斯科谢列梅捷沃国际机场' },
  'Domodedovo International Airport': { name_zh: '莫斯科多莫杰多沃国际机场' },
  'Vnukovo International Airport': { name_zh: '莫斯科伏努科沃国际机场' },
  'Pulkovo Airport': { name_zh: '圣彼得堡普尔科沃机场' },
  'Kazan International Airport': { name_zh: '喀山国际机场' },
  'Platov International Airport': { name_zh: '顿河畔罗斯托夫普拉托夫国际机场' },
  'Sochi International Airport': { name_zh: '索契国际机场' },
  'Vladivostok International Airport': { name_zh: '符拉迪沃斯托克国际机场' },
  'Krasnodar International Airport': { name_zh: '克拉斯诺达尔国际机场' },
  'Ufa International Airport': { name_zh: '乌法国际机场' },
  'Tolmachevo Airport': { name_zh: '新西伯利亚托尔马切沃机场' },
  'Koltsovo Airport': { name_zh: '叶卡捷琳堡科利佐沃机场' },
  
  // 北美洲
  'JFK': { city_zh: '纽约', name_zh: '纽约肯尼迪国际机场' },
  'LGA': { city_zh: '纽约', name_zh: '纽约拉瓜迪亚机场' },
  'EWR': { city_zh: '纽约', name_zh: '纽瓦克自由国际机场' },
  'LAX': { city_zh: '洛杉矶', name_zh: '洛杉矶国际机场' },
  'SFO': { city_zh: '旧金山', name_zh: '旧金山国际机场' },
  'ORD': { city_zh: '芝加哥', name_zh: '芝加哥奥黑尔国际机场' },
  'ATL': { city_zh: '亚特兰大', name_zh: '亚特兰大哈茨菲尔德-杰克逊国际机场' },
  'DFW': { city_zh: '达拉斯', name_zh: '达拉斯-沃斯堡国际机场' },
  'MIA': { city_zh: '迈阿密', name_zh: '迈阿密国际机场' },
  'SEA': { city_zh: '西雅图', name_zh: '西雅图塔科马国际机场' },
  'PHX': { city_zh: '凤凰城', name_zh: '凤凰城天港国际机场' },
  'YVR': { city_zh: '温哥华', name_zh: '温哥华国际机场' },
  'YYZ': { city_zh: '多伦多', name_zh: '多伦多皮尔逊国际机场' },
  'JFK International Airport': { name_zh: '纽约肯尼迪国际机场' },
  'LaGuardia Airport': { name_zh: '纽约拉瓜迪亚机场' },
  'Newark Liberty International Airport': { name_zh: '纽瓦克自由国际机场' },
  'Los Angeles International Airport': { name_zh: '洛杉矶国际机场' },
  'San Francisco International Airport': { name_zh: '旧金山国际机场' },
  'Chicago OHare International Airport': { name_zh: '芝加哥奥黑尔国际机场' },
  'Hartsfield-Jackson Atlanta International Airport': { name_zh: '亚特兰大哈茨菲尔德-杰克逊国际机场' },
  'Dallas/Fort Worth International Airport': { name_zh: '达拉斯-沃斯堡国际机场' },
  'Miami International Airport': { name_zh: '迈阿密国际机场' },
  'Seattle-Tacoma International Airport': { name_zh: '西雅图塔科马国际机场' },
  'Phoenix Sky Harbor International Airport': { name_zh: '凤凰城天港国际机场' },
  'Vancouver International Airport': { name_zh: '温哥华国际机场' },
  'Toronto Pearson International Airport': { name_zh: '多伦多皮尔逊国际机场' },
  
  // 大洋洲
  'SYD': { city_zh: '悉尼', name_zh: '悉尼金斯福德·史密斯国际机场' },
  'MEL': { city_zh: '墨尔本', name_zh: '墨尔本国际机场' },
  'BNE': { city_zh: '布里斯班', name_zh: '布里斯班国际机场' },
  'AKL': { city_zh: '奥克兰', name_zh: '奥克兰国际机场' },
  'Sydney Kingsford Smith Airport': { name_zh: '悉尼金斯福德·史密斯国际机场' },
  'Melbourne Airport': { name_zh: '墨尔本国际机场' },
  'Brisbane International Airport': { name_zh: '布里斯班国际机场' },
  'Auckland International Airport': { name_zh: '奥克兰国际机场' },
  
  // 南美洲
  'GRU': { city_zh: '圣保罗', name_zh: '圣保罗瓜鲁柳斯国际机场' },
  'CGH': { city_zh: '圣保罗', name_zh: '圣保罗孔戈尼亚斯机场' },
  'GIG': { city_zh: '里约热内卢', name_zh: '里约热内卢国际机场' },
  'EZE': { city_zh: '布宜诺斯艾利斯', name_zh: '布宜诺斯艾利斯埃塞萨国际机场' },
  'Sao Paulo Guarulhos International Airport': { name_zh: '圣保罗瓜鲁柳斯国际机场' },
  'Sao Paulo Congonhas Airport': { name_zh: '圣保罗孔戈尼亚斯机场' },
  'Rio de Janeiro International Airport': { name_zh: '里约热内卢国际机场' },
  'Buenos Aires Ezeiza International Airport': { name_zh: '布宜诺斯艾利斯埃塞萨国际机场' },
  
  // 非洲
  'JNB': { city_zh: '约翰内斯堡', name_zh: '约翰内斯堡奥坦博国际机场' },
  'CPT': { city_zh: '开普敦', name_zh: '开普敦国际机场' },
  'CAI': { city_zh: '开罗', name_zh: '开罗国际机场' },
  'Johannesburg OR Tambo International Airport': { name_zh: '约翰内斯堡奥坦博国际机场' },
  'Cape Town International Airport': { name_zh: '开普敦国际机场' },
  'Cairo International Airport': { name_zh: '开罗国际机场' }
};

// 城市中文映射表
const cityZhMapping = {
  // 亚洲
  'Singapore': '新加坡',
  'Beijing': '北京',
  'Shanghai': '上海',
  'Guangzhou': '广州',
  'Shenzhen': '深圳',
  'Chengdu': '成都',
  'Hangzhou': '杭州',
  'Xi\'an': '西安',
  'Nanjing': '南京',
  'Wuhan': '武汉',
  'Chongqing': '重庆',
  'Kunming': '昆明',
  'Hong Kong': '香港',
  'Taipei': '台北',
  'Baotou': '包头',
  'Wuhai': '乌海',
  'Ejin': '额济纳',
  'Bayannur': '巴彦淖尔',
  'Ordos': '鄂尔多斯',
  'Dongsheng': '鄂尔多斯',
  'Hohhot': '呼和浩特',
  'Yichun': '伊春',
  'Heihe': '黑河',
  'Fuyuan': '抚远',
  'Jiansanjiang': '建三江',
  'Yingkou': '营口',
  'Jixi': '鸡西',
  'Wudalianchi': '五大连池',
  'Turpan': '吐鲁番',
  'Xinyuan': '新源',
  'Hami': '哈密',
  'Kuqa': '库车',
  'Fuyun': '富蕴',
  'Kanas': '喀纳斯',
  'Shihezi': '石河子',
  'Shache': '莎车',
  'Tumushuke': '图木舒克',
  'Tashkurgan': '塔什库尔干',
  'Yulin': '榆林',
  'Erenhot': '二连浩特',
  'Manzhouli': '满洲里',
  'Ngari': '阿里',
  'Shigatse': '日喀则',
  'Nyingchi': '林芝',
  'Daocheng': '稻城',
  'Garze': '甘孜',
  'Aba': '阿坝',
  'Libo': '荔波',
  'Chenzhou': '郴州',
  'Wugang': '武冈',
  'Yongzhou': '永州',
  'Baise': '百色',
  'Liuzhou': '柳州',
  'Yulin Guangxi': '玉林',
  'Chamdo': '昌都',
  'Xiahe': '夏河',
  'Longnan': '陇南',
  'Jinchang': '金昌',
  'Qingyang': '庆阳',
  'Hanzhong': '汉中',
  'Ankang': '安康',
  'Shiyan': '十堰',
  'Xinyang': '信阳',
  'Lu\'an': '六安',
  'Ganzhou': '赣州',
  'Jingdezhen': '景德镇',
  'Sanming': '三明',
  'Wuyishan': '武夷山',
  'Linyi': '临沂',
  'Dongying': '东营',
  'Weifang': '潍坊',
  'Rizhao': '日照',
  'Jinan': '济南',
  'Yantai': '烟台',
  'Weihai': '威海',
  'Huai\'an': '淮安',
  'Lianyungang': '连云港',
  'Yangzhou': '扬州',
  'Rugao': '如皋',
  'Taizhou': '台州',
  'Quzhou': '衢州',
  'Zhoushan': '舟山',
  'Yiwu': '义乌',
  'Huangyan': '黄岩',
  'Fuyang': '阜阳',
  'Anqing': '安庆',
  'Huangshan': '黄山',
  'Beihai': '北海',
  'Guilin': '桂林',
  'Zhangjiajie': '张家界',
  'Changde': '常德',
  'Huaihua': '怀化',
  'Xiangyang': '襄阳',
  'Yichang': '宜昌',
  'Enshi': '恩施',
  'Nanyang': '南阳',
  'Luoyang': '洛阳',
  'Handan': '邯郸',
  'Tangshan': '唐山',
  'Qinhuangdao': '秦皇岛',
  'Mangshi': '芒市',
  'Baoshan': '保山',
  'Pu\'er': '普洱',
  'Lincang': '临沧',
  'Zhaotong': '昭通',
  'Wenshan': '文山',
  'Dali': '大理',
  'Lijiang': '丽江',
  'Jinghong': '景洪',
  'Xishuangbanna': '西双版纳',
  'Shangri-La': '香格里拉',
  'Mianyang': '绵阳',
  'Nanchong': '南充',
  'Yibin': '宜宾',
  'Luzhou': '泸州',
  'Dazhou': '达州',
  'Guangyuan': '广元',
  'Kangding': '康定',
  'Jiuzhai': '九寨沟',
  'Zhuhai': '珠海',
  'Jieyang': '揭阳',
  'Meixian': '梅县',
  'Zhanjiang': '湛江',
  'Foshan': '佛山',
  'Zhangjiakou': '张家口',
  'Chengde': '承德',
  'Jining': '济宁',
  'Jinggangshan': '井冈山',
  'Kaili': '凯里',
  'Xingyi': '兴义',
  'Tongren': '铜仁',
  'Liping': '黎平',
  'Zunyi': '遵义',
  'Maotai': '茅台',
  'Yan\'an': '延安',
  'Jiayuguan': '嘉峪关',
  'Dunhuang': '敦煌',
  'Golmud': '格尔木',
  'Delingha': '德令哈',
  'Yushu': '玉树',
  'Zhongwei': '中卫',
  'Delhi': '德里',
  'Shantou': '汕头',
  'Tengchong': '腾冲',
  'Yining': '伊宁',
  'Kashgar': '喀什',
  'Aksu': '阿克苏',
  'Hotan': '和田',
  'Korla': '库尔勒',
  'Tacheng': '塔城',
  'Altay': '阿勒泰',
  'Bole': '博乐',
  'Qiqihar': '齐齐哈尔',
  'Mudanjiang': '牡丹江',
  'Jiamusi': '佳木斯',
  'Mohe': '漠河',
  'Dandong': '丹东',
  'Jinzhou': '锦州',
  'Chaoyang': '朝阳',
  'Chifeng': '赤峰',
  'Tongliao': '通辽',
  'Ulanhot': '乌兰浩特',
  'Arxan': '阿尔山',
  'Datong': '大同',
  'Yuncheng': '运城',
  'Changzhi': '长治',
  'Luliang': '吕梁',
  'Linfen': '临汾',
  'Xinzhou': '忻州',
  'Cangzhou': '沧州',
  'Bengbu': '蚌埠',
  'Chizhou': '池州',
  'Yichun Jiangxi': '宜春',
  'Shangrao': '上饶',
  'Ji\'an': '吉安',
  'Putian': '莆田',
  'Wanzhou': '万州',
  'Anshun': '安顺',
  'Tengchong': '腾冲',
  'Ningbo': '宁波',
  'Wenzhou': '温州',
  'Taizhou Jiangsu': '泰州',
  'Nantong': '南通',
  'Xuzhou': '徐州',
  'Wuxi': '无锡',
  'Changzhou': '常州',
  'Suzhou': '苏州',
  'Zhenjiang': '镇江',
  'Jinhua': '金华',
  'Yanji': '延吉',
  'Osaka': '大阪',
  'Tokyo': '东京',
  'Sapporo': '札幌',
  'Fukuoka': '福冈',
  'Naha': '那霸',
  'Nagoya': '名古屋',
  'Hiroshima': '广岛',
  'Sendai': '仙台',
  'Kagoshima': '鹿儿岛',
  'Kumamoto': '熊本',
  'Nagasaki': '长崎',
  'Oita': '大分',
  'Matsuyama': '松山',
  'Takamatsu': '高松',
  'Aomori': '青森',
  'Asahikawa': '旭川',
  'Okayama': '冈山',
  'Fukushima': '福岛',
  'Miyazaki': '宫崎',
  'Tottori': '鸟取',
  'Obihiro': '带广',
  'Saga': '佐贺',
  'Shirahama': '白滨',
  'Seoul': '首尔',
  'Busan': '釜山',
  'Jeju': '济州岛',
  'Daegu': '大邱',
  'Cheongju': '清州',
  'Gwangju': '光州',
  'Yeosu': '丽水',
  'Pohang': '浦项',
  'Bangkok': '曼谷',
  'Kuala Lumpur': '吉隆坡',
  'Penang': '槟城',
  'Johor Bahru': '新山',
  'Kota Kinabalu': '哥打基纳巴卢(亚庇)',
  'Kuching': '古晋',
  'Sandakan': '山打根',
  'Tawau': '斗湖',
  'Miri': '美里',
  'Langkawi': '兰卡威',
  'Bandar Seri Begawan': '斯里巴加湾市',
  'Manila': '马尼拉',
  'Cebu': '宿务',
  'Davao': '达沃',
  'Iloilo': '伊洛伊洛',
  'Puerto Princesa': '公主港',
  'Cagayan de Oro': '卡加延德奥罗',
  'General Santos': '桑托斯将军城',
  'Bacolod': '巴科洛德',
  'Boracay': '卡提克兰',
  'Zamboanga': '三宝颜',
  'Butuan': '布土安',
  'Kalibo': '卡利博',
  'Jakarta': '雅加达',
  'Denpasar': '巴厘岛',
  'Surabaya': '泗水',
  'Medan': '棉兰',
  'Makassar': '望加锡',
  'Balikpapan': '巴厘巴板',
  'Banjarmasin': '马辰',
  'Yogyakarta': '日惹',
  'Solo': '梭罗',
  'Palembang': '巨港',
  'Padang': '巴东',
  'Pekanbaru': '北干巴鲁',
  'Batam': '巴淡岛',
  'Pontianak': '坤甸',
  'Ambon': '安汶',
  'Manado': '万鸦老',
  'Jayapura': '查亚普拉',
  'Mataram': '马塔兰',
  'Bandung': '万隆',
  'Semarang': '三宝垄',
  'Kendari': '肯达里',
  'Kupang': '古邦',
  'Labuan Bajo': '拉布汉巴乔',
  'Ho Chi Minh City': '胡志明市',
  'Saigon': '胡志明市',
  'Hanoi': '河内',
  'Da Nang': '岘港',
  'Nha Trang': '芽庄',
  'Phu Quoc': '富国',
  'Hai Phong': '海防',
  'Hue': '顺化',
  'Dalat': '大叻',
  'Can Tho': '芹苴',
  'Siem Reap': '暹粒',
  'Phnom Penh': '金边',
  'Sihanoukville': '西哈努克城',
  'Vientiane': '万象',
  'Luang Prabang': '琅勃拉邦',
  'Pakse': '巴色',
  'Yangon': '仰光',
  'Mandalay': '曼德勒',
  'Bagan': '蒲甘',
  'Taunggyi': '东枝',
  'Naypyidaw': '内比都',
  'Bangkok': '曼谷',
  'Chiang Mai': '清迈',
  'Chiang Rai': '清莱',
  'Phuket': '普吉',
  'Krabi': '甲米',
  'Pattaya': '芭堤雅',
  'Koh Samui': '苏梅岛',
  'Udon Thani': '乌隆他尼',
  'Ubon Ratchathani': '乌汶',
  'Hat Yai': '合艾',
  
  // 欧洲
  'London': '伦敦',
  'Paris': '巴黎',
  'Frankfurt': '法兰克福',
  'Munich': '慕尼黑',
  'Amsterdam': '阿姆斯特丹',
  'Brussels': '布鲁塞尔',
  'Zurich': '苏黎世',
  'Geneva': '日内瓦',
  'Madrid': '马德里',
  'Barcelona': '巴塞罗那',
  'Rome': '罗马',
  'Milan': '米兰',
  'Istanbul': '伊斯坦布尔',
  'Ankara': '安卡拉',
  'Izmir': '伊兹密尔',
  'Antalya': '安塔利亚',
  'Qionghai': '琼海',
  'Dubai': '迪拜',
  'Abu Dhabi': '阿布扎比',
  'Sharjah': '沙迦',
  'Doha': '多哈',
  'Manama': '麦纳麦',
  'Kuwait City': '科威特城',
  'Muscat': '马斯喀特',
  'Riyadh': '利雅得',
  'Jeddah': '吉达',
  'Medina': '麦地那',
  'Dammam': '达曼',
  'Dhahran': '达兰',
  'Taif': '塔伊夫',
  'Najran': '奈季兰',
  'Amman': '安曼',
  'Aqaba': '亚喀巴',
  'Beirut': '贝鲁特',
  'Baghdad': '巴格达',
  'Basra': '巴士拉',
  'Erbil': '埃尔比勒',
  'Najaf': '纳杰夫',
  'Sulaymaniyah': '苏莱曼尼亚',
  'Tehran': '德黑兰',
  'Mashhad': '马什哈德',
  'Isfahan': '伊斯法罕',
  'Shiraz': '设拉子',
  'Tabriz': '大不里士',
  'Kish Island': '基什岛',
  'Cairo': '开罗',
  'Hurghada': '赫尔格达',
  'Sharm el-Sheikh': '沙姆沙伊赫',
  'Aswan': '阿斯旺',
  'Alexandria': '亚历山大',
  'Luxor': '卢克索',
  'Marsa Alam': '马尔萨阿拉姆',
  'Tunis': '突尼斯',
  'Monastir': '莫纳斯提尔',
  'Djerba': '杰尔巴',
  'Algiers': '阿尔及尔',
  'Oran': '奥兰',
  'Constantine': '君士坦丁',
  'Marrakech': '马拉喀什',
  'Casablanca': '卡萨布兰卡',
  'Fez': '非斯',
  'Agadir': '阿加迪尔',
  'Rabat': '拉巴特',
  'Tangier': '丹吉尔',
  'Oujda': '乌季达',
  'Tetouan': '得土安',
  'Nador': '纳祖尔',
  'Vienna': '维也纳',
  'Copenhagen': '哥本哈根',
  'Stockholm': '斯德哥尔摩',
  'Gothenburg': '哥德堡',
  'Malmo': '马尔默',
  'Oslo': '奥斯陆',
  'Bergen': '卑尔根',
  'Stavanger': '斯塔万格',
  'Trondheim': '特隆赫姆',
  'Tromso': '特罗姆瑟',
  'Narvik': '纳尔维克',
  'Haugesund': '海于格松',
  'Alesund': '奥勒松',
  'Helsinki': '赫尔辛基',
  'Dublin': '都柏林',
  'Cork': '科克',
  'Edinburgh': '爱丁堡',
  'Manchester': '曼彻斯特',
  'Birmingham': '伯明翰',
  'Bristol': '布里斯托尔',
  'Newcastle': '纽卡斯尔',
  'Glasgow': '格拉斯哥',
  'Aberdeen': '阿伯丁',
  'Belfast': '贝尔法斯特',
  'Dusseldorf': '杜塞尔多夫',
  'Berlin': '柏林',
  'Hamburg': '汉堡',
  'Cologne': '科隆',
  'Stuttgart': '斯图加特',
  'Hanover': '汉诺威',
  'Nuremberg': '纽伦堡',
  'Dresden': '德累斯顿',
  'Bremen': '不莱梅',
  'Leipzig': '莱比锡',
  'Venice': '威尼斯',
  'Bologna': '博洛尼亚',
  'Naples': '那不勒斯',
  'Florence': '佛罗伦萨',
  'Catania': '卡塔尼亚',
  'Palermo': '巴勒莫',
  'Bari': '巴里',
  'Turin': '都灵',
  'Genoa': '热那亚',
  'Verona': '维罗纳',
  'Pisa': '比萨',
  'Cagliari': '卡利亚里',
  'Olbia': '奥尔比亚',
  'Athens': '雅典',
  'Thessaloniki': '塞萨洛尼基',
  'Heraklion': '伊拉克利翁',
  'Rhodes': '罗德岛',
  'Mykonos': '米科诺斯',
  'Santorini': '圣托里尼',
  'Corfu': '科孚',
  'Lisbon': '里斯本',
  'Porto': '波尔图',
  'Funchal': '丰沙尔',
  'Ponta Delgada': '蓬塔德尔加达',
  'Warsaw': '华沙',
  'Krakow': '克拉科夫',
  'Gdansk': '格但斯克',
  'Wroclaw': '弗罗茨瓦夫',
  'Poznan': '波兹南',
  'Katowice': '卡托维兹',
  'Prague': '布拉格',
  'Budapest': '布达佩斯',
  'Bratislava': '布拉迪斯拉发',
  'Bucharest': '布加勒斯特',
  'Cluj-Napoca': '克卢日-纳波卡',
  'Sofia': '索菲亚',
  'Skopje': '斯科普里',
  'Podgorica': '波德戈里察',
  'Tivat': '蒂瓦特',
  'Belgrade': '贝尔格莱德',
  'Zagreb': '萨格勒布',
  'Split': '斯普利特',
  'Dubrovnik': '杜布罗夫尼克',
  'Ljubljana': '卢布尔雅那',
  'Sarajevo': '萨拉热窝',
  'Tirana': '地拉那',
  'Moscow': '莫斯科',
  'Saint Petersburg': '圣彼得堡',
  'Kazan': '喀山',
  'Rostov-on-Don': '顿河畔罗斯托夫',
  'Sochi': '索契',
  'Vladivostok': '符拉迪沃斯托克(海参崴)',
  'Krasnodar': '克拉斯诺达尔',
  'Ufa': '乌法',
  'Novosibirsk': '新西伯利亚',
  'Yekaterinburg': '叶卡捷琳堡',
  // 印度
  'New Delhi': '新德里',
  'Mumbai': '孟买',
  'Bangalore': '班加罗尔',
  'Chennai': '金奈',
  'Kolkata': '加尔各答',
  'Hyderabad India': '海德拉巴',
  'Ahmedabad': '艾哈迈达巴德',
  'Goa': '果阿',
  'Kochi': '科钦',
  'Pune': '浦那',
  'Guwahati': '古瓦哈提',
  'Lucknow': '勒克瑙',
  'Jaipur': '斋浦尔',
  'Varanasi': '瓦拉纳西',
  'Chandigarh': '昌迪加尔',
  'Nagpur': '那格浦尔',
  'Vijayawada': '维杰亚瓦达',
  'Madurai': '马杜赖',
  'Thiruvananthapuram': '特里凡得琅',
  'Visakhapatnam': '维沙卡帕特南',
  'Bagdogra': '巴多格拉',
  'Ranchi': '兰契',
  'Patna': '巴特那',
  'Srinagar': '斯利那加',
  'Leh': '列城',
  'Jodhpur': '焦特布尔',
  'Udaipur': '乌代布尔',
  'Agra': '阿格拉',
  'Port Blair': '布莱尔港',
  // 中亚
  'Astana': '阿斯塔纳',
  'Almaty': '阿拉木图',
  'Aktau': '阿克套',
  'Oskemen': '厄斯克门',
  'Pavlodar': '巴甫洛达尔',
  'Ganja': '占贾',
  'Baku': '巴库',
  'Yerevan': '埃里温',
  'Tbilisi': '第比利斯',
  'Kyiv': '基辅',
  'Odesa': '敖德萨',
  // 中亚五国
  'Dushanbe': '杜尚别',
  'Tashkent': '塔什干',
  'Samarkand': '撒马尔罕',
  'Bukhara': '布哈拉',
  'Namangan': '纳曼干',
  'Fergana': '费尔干纳',
  'Urgench': '乌尔根奇',
  'Nukus': '努库斯',
  'Bishkek': '比什凯克',
  'Osh': '奥什',
  'Ashgabat': '阿什哈巴德',
  'Turkmenabat': '土库曼纳巴德',
  // 南亚
  'Kathmandu': '加德满都',
  'Pokhara': '博卡拉',
  'Lumbini': '蓝毗尼',
  'Male': '马累',
  'Colombo': '科伦坡',
  'Dhaka': '达卡',
  'Chittagong': '吉大港',
  'Sylhet': '锡尔赫特',
  'Rajshahi': '拉杰沙希',
  'Islamabad': '伊斯兰堡',
  'Karachi': '卡拉奇',
  'Lahore': '拉合尔',
  'Peshawar': '白沙瓦',
  'Sialkot': '锡亚尔科特',
  'Faisalabad': '费萨拉巴德',
  'Multan': '木尔坦',
  // 非洲
  'Addis Ababa': '亚的斯亚贝巴',
  'Nairobi': '内罗毕',
  'Mombasa': '蒙巴萨',
  'Dar es Salaam': '达累斯萨拉姆',
  'Zanzibar': '桑给巴尔',
  'Entebbe': '恩德培',
  'Kigali': '基加利',
  'Harare': '哈拉雷',
  'Bulawayo': '布拉瓦约',
  'Lusaka': '卢萨卡',
  'Mauritius': '毛里求斯',
  'Victoria Seychelles': '维多利亚',
  'Antananarivo': '塔那那利佛',
  'Lagos': '拉各斯',
  'Abuja': '阿布贾',
  'Kano': '卡诺',
  'Port Harcourt': '哈科特港',
  'Accra': '阿克拉',
  'Abidjan': '阿比让',
  'Dakar': '达喀尔',
  'Durban': '德班',
  'Port Elizabeth': '伊丽莎白港',
  'George': '乔治',
  // 南美
  'Sao Paulo': '圣保罗',
  'Rio de Janeiro': '里约热内卢',
  'Brasilia': '巴西利亚',
  'Belo Horizonte': '贝洛奥里藏特',
  'Salvador': '萨尔瓦多',
  'Recife': '累西腓',
  'Fortaleza': '福塔雷萨',
  'Porto Alegre': '阿雷格里港',
  'Curitiba': '库里奇巴',
  'Florianopolis': '弗洛里亚诺波利斯',
  'Manaus': '马瑙斯',
  'Belem': '贝伦',
  'Campinas': '坎皮纳斯',
  'Buenos Aires': '布宜诺斯艾利斯',
  'Cordoba Argentina': '科尔多瓦',
  'Mendoza': '门多萨',
  'Puerto Iguazu': '伊瓜苏港',
  'Santiago': '圣地亚哥',
  'Lima': '利马',
  'Cusco': '库斯科',
  'Bogota': '波哥大',
  'Medellin': '麦德林',
  'Cali': '卡利',
  'Cartagena': '卡塔赫纳',
  'Barranquilla': '巴兰基亚',
  'Quito': '基多',
  'Guayaquil': '瓜亚基尔',
  'Caracas': '加拉加斯',
  'Montevideo': '蒙得维的亚',
  'Asuncion': '亚松森',
  'La Paz': '拉巴斯',
  'Santa Cruz': '圣克鲁斯',
  'Quibdo': '基布多',
  
  // 北美洲
  'New York': '纽约',
  'Los Angeles': '洛杉矶',
  'San Francisco': '旧金山',
  'Chicago': '芝加哥',
  'Atlanta': '亚特兰大',
  'Dallas': '达拉斯',
  'Miami': '迈阿密',
  'Seattle': '西雅图',
  'Phoenix': '凤凰城',
  'Vancouver': '温哥华',
  'Toronto': '多伦多',
  
  // 大洋洲
  'Sydney': '悉尼',
  'Melbourne': '墨尔本',
  'Brisbane': '布里斯班',
  'Auckland': '奥克兰',
  
  // 南美洲
  'Sao Paulo': '圣保罗',
  'Rio de Janeiro': '里约热内卢',
  'Buenos Aires': '布宜诺斯艾利斯',
  
  // 非洲
  'Johannesburg': '约翰内斯堡',
  'Cape Town': '开普敦',
  'Cairo': '开罗'
};

// 国家国旗映射表
const countryFlagMapping = {
  'SG': '🇸🇬', // 新加坡
  'CN': '🇨🇳', // 中国
  'JP': '🇯🇵', // 日本
  'KR': '🇰🇷', // 韩国
  'TH': '🇹🇭', // 泰国
  'MY': '���', // 马来西亚
  'BN': '🇧🇳', // 文莱
  'PH': '🇵🇭', // 菲律宾
  'ID': '🇮🇩', // 印度尼西亚
  'VN': '🇻🇳', // 越南
  'KH': '🇰🇭', // 柬埔寨
  'LA': '🇱🇦', // 老挝
  'MM': '🇲🇲', // 缅甸
  'HK': '🇭🇰', // 香港
  'TW': '🇹🇼', // 台湾
  'GB': '🇬🇧', // 英国
  'FR': '🇫🇷', // 法国
  'DE': '🇩🇪', // 德国
  'NL': '🇳🇱', // 荷兰
  'BE': '🇧🇪', // 比利时
  'CH': '🇨🇭', // 瑞士
  'ES': '🇪🇸', // 西班牙
  'IT': '🇮🇹', // 意大利
  'TR': '🇹🇷', // 土耳其
  'US': '🇺🇸', // 美国
  'CA': '🇨🇦', // 加拿大
  'AU': '🇦🇺', // 澳大利亚
  'NZ': '🇳🇿', // 新西兰
  'BR': '🇧🇷', // 巴西
  'AR': '🇦🇷', // 阿根廷
  'ZA': '🇿🇦', // 南非
  'AE': '🇦🇪', // 阿联酋
  'QA': '🇶🇦', // 卡塔尔
  'BH': '🇧🇭', // 巴林
  'KW': '🇰🇼', // 科威特
  'OM': '🇴🇲', // 阿曼
  'SA': '🇸🇦', // 沙特阿拉伯
  'JO': '🇯🇴', // 约旦
  'LB': '🇱🇧', // 黎巴嫩
  'IQ': '🇮🇶', // 伊拉克
  'IR': '🇮🇷', // 伊朗
  'EG': '🇪🇬', // 埃及
  'TN': '🇹🇳', // 突尼斯
  'DZ': '🇩🇿', // 阿尔及利亚
  'MA': '🇲🇦', // 摩洛哥
  'AT': '🇦🇹', // 奥地利
  'DK': '🇩🇰', // 丹麦
  'SE': '🇸🇪', // 瑞典
  'NO': '🇳🇴', // 挪威
  'FI': '🇫🇮', // 芬兰
  'IE': '🇮🇪', // 爱尔兰
  'PT': '🇵🇹', // 葡萄牙
  'GR': '🇬🇷', // 希腊
  'PL': '🇵🇱', // 波兰
  'CZ': '🇨🇿', // 捷克
  'HU': '🇭🇺', // 匈牙利
  'RO': '🇷🇴', // 罗马尼亚
  'BG': '🇧🇬', // 保加利亚
  'RS': '🇷🇸', // 塞尔维亚
  'HR': '🇭🇷', // 克罗地亚
  'SI': '🇸🇮', // 斯洛文尼亚
  'BA': '🇧🇦', // 波黑
  'AL': '🇦🇱', // 阿尔巴尼亚
  'MK': '🇲🇰', // 北马其顿
  'ME': '🇲🇪', // 黑山
  'SK': '🇸🇰', // 斯洛伐克
  'RU': '🇷🇺', // 俄罗斯
  'IN': '🇮🇳', // 印度
  'KZ': '🇰🇿', // 哈萨克斯坦
  'UZ': '🇺🇿', // 乌兹别克斯坦
  'KG': '🇰🇬', // 吉尔吉斯斯坦
  'TJ': '🇹🇯', // 塔吉克斯坦
  'TM': '🇹🇲', // 土库曼斯坦
  'AZ': '🇦🇿', // 阿塞拜疆
  'AM': '🇦🇲', // 亚美尼亚
  'GE': '🇬🇪', // 格鲁吉亚
  'UA': '🇺🇦', // 乌克兰
  'NP': '🇳🇵', // 尼泊尔
  'MV': '🇲🇻', // 马尔代夫
  'LK': '🇱🇰', // 斯里兰卡
  'BD': '🇧🇩', // 孟加拉国
  'PK': '🇵🇰', // 巴基斯坦
  'ET': '🇪🇹', // 埃塞俄比亚
  'KE': '🇰🇪', // 肯尼亚
  'TZ': '🇹🇿', // 坦桑尼亚
  'UG': '🇺🇬', // 乌干达
  'RW': '🇷🇼', // 卢旺达
  'ZW': '🇿🇼', // 津巴布韦
  'ZM': '🇿🇲', // 赞比亚
  'MU': '🇲🇺', // 毛里求斯
  'SC': '🇸🇨', // 塞舌尔
  'MG': '🇲🇬', // 马达加斯加
  'NG': '🇳🇬', // 尼日利亚
  'GH': '🇬🇭', // 加纳
  'CI': '🇨🇮', // 科特迪瓦
  'SN': '🇸🇳', // 塞内加尔
  'BR': '🇧🇷', // 巴西
  'AR': '🇦🇷', // 阿根廷
  'CL': '🇨🇱', // 智利
  'PE': '🇵🇪', // 秘鲁
  'CO': '🇨🇴', // 哥伦比亚
  'EC': '🇪🇨', // 厄瓜多尔
  'VE': '🇻🇪', // 委内瑞拉
  'UY': '🇺🇾', // 乌拉圭
  'PY': '🇵🇾', // 巴拉圭
  'BO': '🇧🇴', // 玻利维亚
};

export { airportZhMapping, cityZhMapping, countryFlagMapping };
